### ISSUE TITLE
Network Operations Centre

### ISSUE THREAD

**Issue by vannut** [brocaar/lora-app-server#1]
It would be very cool if the lora-app-server would be able to provide an overview off the gateways reporting to it. 

Key-metrics like rx/tx per minute per gateway or server wide. The average RSSI or SNR

What kind of metrics are more interesting to know about? Things like the cpu-load on the gateway would also be very nice; or the status of a certain GPIO pin (on a raspberry Pi) connected to a temperature sensor. Although these last metrics are not transmitted by default, they would be very cool to have :)

**Comment by hecko** [comment]
@vannut the infromation are available by subscribing to the gateway MQTT topic - we use this stream of data to push information to our own monitoring system + use zabbix to monitor the gateways. This is a very neat way to integrate the loraserver to your NOC solution. (easy to do for zabbix, nagios...)

**Comment by vannut** [comment]
Never new there was a Gateway MQtt topic :) 
What would be the default data in such a message? Would the data sent in that topic be customizable? 
I do not have a working instance of the lora-app-server running; so i'm not able to check it.

**Comment by hecko** [comment]
The data sent to that topis are almost identical (if not completely identical) to the data that packet forwarder sends out via UDP port.

**Comment by brocaar** [comment]
Guys, I'm looking forward to your feedback on https://github.com/brocaar/lora-app-server/pull/42! I've added some screenshots to give you an idea of the upcoming changes.

**Comment by brocaar** [comment]
Gateway management + stats has been released!
