### ISSUE TITLE
error about organization_id in gateway table

### ISSUE THREAD

**Issue by SoHyunYang** [brocaar/lora-app-server#105]
Hi~

I'm wonder why below error appeared when i execute lora-app-server.exe.

**level=error msg="gwmigrate: list gateways error (will retry): rpc error: code = 2 desc = missing destination name organization_id in *[]gateway.Gateway"**

![image](https://user-images.githubusercontent.com/17341294/27629144-58ffbe5e-5c2c-11e7-92c9-c91a73d9e5c3.png)

I think  that problem is associated with the  gateway table in postgresql database.

Must i write the organization_id in gateway table?

If so, how can i decide organization_id and put it in gateway table?

![image](https://user-images.githubusercontent.com/17341294/27629165-6a5501aa-5c2c-11e7-8660-729bab87953d.png)

How can i fix this problem?

**Comment by brocaar** [comment]
Could you check the following?

1. Make sure that Both LoRa Server and LoRa App Server are using different databases
2. Make sure you're starting both services with `--db-automigrate` flag
