### ISSUE TITLE
Start lora-app-server in http

### ISSUE THREAD

**Issue by mirk8xr** [brocaar/lora-app-server#106]
Is it possible start lora-app-server using http and not https with TLS certificate? If I comment HTTP_TLS_CERT and HTTP_TLS_KEY lora-app-failed to start.

**Comment by brocaar** [comment]
No, this is not possible.

> The http server for serving the web-interface and API (both gRPC as the RESTful JSON api) must be secured by using a TLS certificate.

https://docs.loraserver.io/lora-app-server/install/config/

This is because the gRPC and REST api are served on the same interface and this is only possible when using TLS (because a http/2 is needed).
