### ISSUE TITLE
Can't add new gateway -> mac adress field

### ISSUE THREAD

**Issue by D4rkness** [brocaar/lora-app-server#110]
I have a issue.
I cant add a new gateway to over the app-server.

javasciprt line:
`id:"mac",type:"text",placeholder:"0000000000000000",pattern:"[A-Fa-f0-9]{16}",required`

javascript shows the mac-adress requieres a string of 16 chars and with the pattern.

So i can#t add a new gateway following mac adresses due to the pattern restriction

A8:40:41:16:8E:FE
or
A8-40-41-16-8E-FE

And this also doesn't work because the string has not 16 chars:
A84041168EFE

any solution for the problem ?

Thank you

**Comment by brocaar** [comment]
Please note you need to use the MAC address as configured in the packet-forwarder configuration, not the ethernet MAC address. This packet-forwarder MAC address is exactly 16 chars.

**Comment by D4rkness** [comment]
oh ok thank you !
