### ISSUE TITLE
Add node with manufacturer preconfigured DevEUI 

### ISSUE THREAD

**Issue by ehsanmqn** [brocaar/lora-app-server#111]
Dear Broccar, 
Thank you for your great work. I've already set up the LoRa server completely and added two gateway working with the network. For now, I need to add a node with preconfigured DevEUI to the application server. Is it possible to guide how I can do that, please?

**Comment by brocaar** [comment]
Please see https://docs.loraserver.io/lora-app-server/use/nodes/. You need to create an application first, then you can add new nodes to this application and enter the DevEUI, AppEUI and AppKey as provided by your node.

**Comment by ehsanmqn** [comment]
Thank you so much.
