### ISSUE TITLE
about http-tls-cert

### ISSUE THREAD

**Issue by lihao0107new** [brocaar/lora-app-server#12]
Hello brocaar:
        I want to know func "mustGetHTTPHandler" create httpHandler is for grpc?
I don't have "http-tls-cert" and "http-tls-key" .  so the mustGetJSONGateway return err.

**Comment by hecko** [comment]
There is a documentation on how to create the keys here: 
https://docs.loraserver.io/lora-app-server/api/#security-tls

**Comment by brocaar** [comment]
@lihao0107new the TLS certificates are required. The technical reason behind it is that gRPC uses http/2 as a transport and Go only enables the http/2 server (which is shared with the REST api) when TLS is enabled.
