### ISSUE TITLE
Changing RX window doesn't work

### ISSUE THREAD

**Issue by iBrick** [brocaar/lora-app-server#123]
### Is this a bug or a feature request?
Bug
### What did you expect?
When I change 'Receive window' option I expect that receive window will be changed and so will frequency (RX1 - is the same downlink frequency as uplink frequency, RX2 - 869525)
### What happened?
In reality frequency doesn't change and it can be seen in frame log.
### What version are your using?
0.10.1
### How can your issue be reproduced?
1. Create device (I created ABP device). 
2. Send uplink, send downlink.
3. Change RX window. 
4. Send uplink, send downlink.
5. Check Frame log and see that frequency didn't change.
6. Remove device. Create it again with same DevAddr, etc (ABP) but with new RX window. 
7. Send uplink, downlink. 
You'll see that this time it is changed.
### Could you share your log output?
![2017-07-26](https://user-images.githubusercontent.com/4927627/28630017-c0f676d6-7231-11e7-9d90-626fef1494f1.png)

**Comment by brocaar** [comment]
Please not that you need to re-activate your node in order for the changes to kick in. See also the note above the form:

> Please note that changes made below (when updating a node) only have effect after (re)activating the node (either ABP or OTAA).

**Comment by brocaar** [comment]
Could you let me know if your issue has been solved?

**Comment by iBrick** [comment]
Hi, 
Yes this worked. It is a little bit confusing about 'reactivating' in ABP mode. Because the only way to do this is deleting node and creating it again. Some devices that I've bought which work in ABP doesn't allow to change keys thus can't be 'reactivated'.
