### ISSUE TITLE
Application EUI in ABP

### ISSUE THREAD

**Issue by camilorojasg** [brocaar/lora-app-server#124]
Hello,

I would like to know what is the purpose of the AppEUI in server, in ABP mode, since the motes doesn't need such configuration in ABP mode and the lora-app-server UI doesn't allow me to leave that field blank.

Thanks.

**Comment by brocaar** [comment]
Actually, there is no real purpose for it in case of ABP an you can set it to anything you want. I'll probably clean this up when LoRaWAN 1.1 is out as the AppEUI will be changed to JoinEUI.
