### ISSUE TITLE
imports bufio: unrecognized import path "bufio"

### ISSUE THREAD

**Issue by y0913011011** [brocaar/lora-app-server#132]
### Is this a bug or a feature request?
No
### What happened?
lchw@vm:lora-app-server$ make requirements ui-requirements
Installing development tools
package github.com/golang/lint/golint
	imports bufio: unrecognized import path "bufio"
package github.com/golang/lint/golint
	imports bytes: unrecognized import path "bytes"
package github.com/golang/lint/golint
	imports flag: unrecognized import path "flag"
package github.com/golang/lint/golint
	imports fmt: unrecognized import path "fmt"
package github.com/golang/lint/golint
	imports github.com/golang/lint
	imports go/ast: unrecognized import path "go/ast"

### What version are your using?
lchw@vm:~$ go version
go version go1.2.1 linux/386

**Comment by brocaar** [comment]
You're using Go 1.2.1, the [docs](https://docs.loraserver.io/lora-app-server/community/source/) says

> Make sure you have Go installed (1.7+) ...

😉
