### ISSUE TITLE
sh: 1: react-scripts: not found

### ISSUE THREAD

**Issue by y0913011011** [brocaar/lora-app-server#133]
### Is this a bug or a feature request?
No
### What did you expect?
make build pass
### What happened?
lchw@vm:lora-app-server$ make 
Building ui

> ui@0.1.0 build /home/lchw/gowork/src/github.com/brocaar/lora-app-server/ui
> react-scripts build

sh: 1: react-scripts: not found
npm ERR! weird error 127
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! not ok code 0
make: *** [ui/build] 错误 1

### What version are your using?
go version go1.9rc2 linux/386

**Comment by brocaar** [comment]
You probably did not install the ui requirements, please see https://docs.loraserver.io/lora-app-server/community/source/.
