### ISSUE TITLE
Possibility to deactivate Node without deleting it

### ISSUE THREAD

**Issue by kdannen** [brocaar/lora-app-server#136]
#### Feature Request
For testing purposes it is sometimes useful to ignore a node/device. Currently the only possibility to achieve this is by deleting the node. But this means I have to create it completely from scratch when I want to use it again. A small "deactivate" or "pause" button would solve this.

**Comment by bhatanku1** [comment]
Hey @brocaar ! Could you please let us know if this feature is planned any time soon. I am also currently deleting the device when I need to deactivate it. 

Thanks a lot.
Regards
Ankur

**Comment by brocaar** [comment]
It has been implemented. One can now simply call `DELETE /api/devices/[DevEUI]/activation` to delete the device-activation (not the device) :)

This will be included in the next release.

**Comment by bhatanku1** [comment]
That's awesome @brocaar :) . Thank you very much. Do you already have an estimated date for the next release? 
Regards
Ankur

**Comment by brocaar** [comment]
Probably next week or the week after.

**Comment by bhatanku1** [comment]
Great! Thanks a ton!
