### ISSUE TITLE
Add a node to postgre, dev_addr, app_s_key, nwk_s_key can't be added

### ISSUE THREAD

**Issue by artuguy** [brocaar/lora-app-server#143]
Hi, Everyone:
     When i added an node to postgre by cmd line as below:
    INSERT INTO node (dev_eui, app_eui, app_key, rx_delay, rx1_dr_offset, rx_window, rx2_dr, app_s_key, nwk_s_key, dev_addr, name, relax_fcnt, adr_interval, installation_margin, application_id, description, is_abp, is_class_c, use_application_settings) VALUES (E'\\x0000002017081800', E'\\x526973696e674846', E'\\x2b7e151628aed2a6abf7158809cf4f3c', 0,0,0,0, E'\\x2B7E151628AED2A6ABF7158809CF4F3C', E'\\x2B7E151628AED2A6ABF7158809CF4F3C',E'\\x20170818','stwe0', true, 0,0.00,2,'stwe',true,false,false);

node can be added, but dev_addr, app_s_key, nwk_s_key can't be added,  check from web page, they are still zero. 
type the data to the domain on the  web page , it is inputed correctly.
How did it do?
How can I add node batchly using APB ?

Thanks. 
### Is this a bug or a feature request?
yes
### What did you expect?
add node through cmd line bulkly.
### What version are your using?
0.11.0

**Comment by brocaar** [comment]
Please use the API:

* `POST /api/nodes` - to create a node
* `POST /api/nodes/{devEUI}/activation` - to activate a node

Never write data directly to the database as you're bypassing a lot of logic that is being executed!
