### ISSUE TITLE
change "Sirupsen/logrus" to "sirupsen/logrus" ?

### ISSUE THREAD

**Issue by hcwhan** [brocaar/lora-app-server#148]
can i add a new Pull Requests
chenge `import "github.com/Sirupsen/logrus"` to `import "github.com/sirupsen/logrus"`
Because the official is lowercase, and I want to customize it in my project. For add linenumber and filename in log.
(ps:  https://gist.github.com/hcwhan/c7b0cd986db2a63ab3fc05c6f55c64af)

**Comment by brocaar** [comment]
Yes, feel free to create a pull-request :-)
