### ISSUE TITLE
port 8080

### ISSUE THREAD

**Issue by artuguy** [brocaar/lora-app-server#152]
### What happened?
Web_UI  can't be loged
### Could you share your log output?
Hi, 
       I have deployed lora-app-server onto my  bandwagon VPS,  It is ubuntu 16.04, but https://x.x.x.x:8080 can't log to
lora-app-server,   I  type netstat -an|grep 8080 , it display nothing.
What's wrong with it ?
Please help me.
thanks

**Comment by brocaar** [comment]
Please use https://forum.loraserver.io for support questions. There are already a couple of topics that might cover your issue.
