### ISSUE TITLE
Can storage of frames be limited to some count?

### ISSUE THREAD

**Issue by Ankitjd18** [brocaar/lora-app-server#154]
### Is this a bug or a feature request?
Query
### What did you expect?
Can we limit the number of uplink/downlink stored in the db? Is there some function to disable saving frames at all? What is the current implementation here?

**Comment by brocaar** [comment]
> Can we limit the number of uplink/downlink stored in the db?

You could run a cronjob which would purge all rows older than a given timestamp. There is an index on the `created_at` column for this reason. E.g. your query could be something like:

```sql
delete from frame_log where created_at < now() - interval '30 days';
```

> Is there some function to disable saving frames at all?

See:

```
--log-node-frames                       log uplink and downlink frames to the database [$LOG_NODE_FRAMES]
```

https://docs.loraserver.io/loraserver/install/config/
