### ISSUE TITLE
where Uplink frame-counter and Downlink frame-counter restore in postgres

### ISSUE THREAD

**Issue by waytai** [brocaar/lora-app-server#155]
### Is this a bug or a feature request?
request
### What did you expect?
Uplink frame-counter and Downlink frame-counter in postgres

**Comment by waytai** [comment]
![image](https://user-images.githubusercontent.com/3124188/30586576-02648444-9d63-11e7-8643-22d41cc696f9.png)

**Comment by brocaar** [comment]
They are stored as part of the node-session in LoRa Server.

**Comment by waytai** [comment]
I have found that it restored in redis. thank you
