### ISSUE TITLE
Not able to view Network session key using pgadmin client

### ISSUE THREAD

**Issue by Richaagarwalrn** [brocaar/lora-app-server#156]
### Is this a bug or a feature request?
question
### What did you expect?
Is their any encoding on network and application session keys
### What happened?
I am not able to view Network and application session keys  in database using pgadmin client

**Comment by brocaar** [comment]
You need to use the `GetNodeSession` API method: https://github.com/brocaar/loraserver/blob/master/api/ns/ns.proto#L13. See also: https://docs.loraserver.io/loraserver/integrate/api/.
