### ISSUE TITLE
I can send down data through the API.How do I use API interfaces to see the payload of the node's uplink data?Are we missing something? Please let us know what are we missing.

### ISSUE THREAD

**Issue by SnailQuick** [brocaar/lora-app-server#158]

**Comment by brocaar** [comment]
There is no API method for uplink data. Please see: https://docs.loraserver.io/lora-app-server/integrate/data/

**Comment by SnailQuick** [comment]
very thanks！

**Comment by SnailQuick** [comment]
API -> Node  ->
![image](https://user-images.githubusercontent.com/32405301/31270847-972dc402-aab8-11e7-8567-0026823baefd.png)
get information :   " "phyPayloadJSON": "{\"mhdr\":{\"mType\":\"ConfirmedDataDown\",\"major\":\"LoRaWANR1\"},\"macPayload\":{\"fhdr\":{\"devAddr\":\"07d1dbda\",\"fCtrl\":{\"adr\":false,\"adrAckReq\":false,\"ack\":true,\"fPending\":false},\"fCnt\":6,\"fOpts\":null},\"fPort\":44,\"frmPayload\":[{\"bytes\":\"nsRouyuy\"}]},\"mic\":\"936437a8\"}"”

"nsRouyuy" What's the data?
