### ISSUE TITLE
Feature request:  Display gateway bridge, server and app server versions

### ISSUE THREAD

**Issue by sslupsky** [brocaar/lora-app-server#160]
### Is this a bug or a feature request?
Feature request

### What did you expect?
Would it be possible to have a page in the App Server that displayed the current versions of the installed software for the Gateway Bridge, Server and App Server?

**Comment by brocaar** [comment]
I don't think that would work. LoRa App Server should not have access to LoRa Gateway Bridge as this sits in-between the gateway (or on the gateway) and LoRa Server. Also, LoRa App Server could be connected to one LoRa Server instance part of a cluster. So the information you would see would only reflect a single instance, not your complete deployment.

**Comment by brocaar** [comment]
See #316
