### ISSUE TITLE
Downlink in class C nodes only being sent on receiving uplink

### ISSUE THREAD

**Issue by Ankitjd18** [brocaar/lora-app-server#166]
### What did you expect?
Downlink to be sent immediately as also shows immediately to true in frame logs
### What happened?
Downlink was sent upon receiving the next uplink as in class A nodes
Is there some setting required in order for class C nodes to send downlink properly.

**Comment by brocaar** [comment]
Yes, you need to configure the application or node as Class-C device. Also you need to re-activate the node after changing this setting.

**Comment by Ankitjd18** [comment]
I have configured the node as Class-C device and also re-activated but it still is behaving like Class-A device.
In frame logs, I can see the `immediately` field to be `true` but still sent on receiving a uplink.

**Comment by brocaar** [comment]
To be sure, that is not because your application sends downlink frames on uplink?

**Comment by Ankitjd18** [comment]
`immediately` field is set to be `true` for Class-C devices so that downlink can be sent by the server immediately. This field is set to `false` in Class-A devices. This is an observation I made.
I am still not sure of what is causing this issue. I have tried several times, but downlink reaches the device only after it has sent a uplink to the server.

**Comment by kammyy** [comment]
@brocaar : Hi, our application is not configured to send downlink upon receiving uplink.

We send the downlink command to node from application and after doing so we can see the downlink listed in frame logs section with immediately tags as "true". But the downlink is sent to node after next uplink.

**Comment by Ankitjd18** [comment]
We tried switching between `OTA` and `ABP`. It works fine in case of `OTA` device but not for `ABP`. Is this something to do be the activation?

**Comment by kammyy** [comment]
@brocaar : Any comments/suggestions ?

thnx

**Comment by brocaar** [comment]
It might be related to your device firmware, this is hard for me to test. Could you also test if your issue persists with the latest release: https://forum.loraserver.io/t/release-lora-server-0-22-0-lora-app-server-0-14-x-read-carefully/350

**Comment by Ankitjd18** [comment]
Sure, we will test with the latest release and let you know of our findings.

**Comment by brocaar** [comment]
I've just released LoRa App Server 0.15.0 and LoRa Server 0.23.0. This new release has refactored queue logic (LoRa Server is now responsible for the downlink queue). Also you'll get a (n)ACK on confirmed Class-C transmissions.
