### ISSUE TITLE
Confirmed Downlink retry

### ISSUE THREAD

**Issue by kammyy** [brocaar/lora-app-server#168]
### What happened?
When sending a confirmed downlink to a C type node, when the device does not send "ACK" for the downlink then the server sends the downlink multiple times.

For how many times the server keeps on sending the downlink to node in case the ACK does not come from the node ?

How to change this number of retry for downlink ?

thnx

**Comment by kammyy** [comment]
@brocaar : any comments ?

Thanks

**Comment by brocaar** [comment]
Currently it will be re-sent until an ACK is received. I'm currently refactoring the downlink queue and it will be possible to give a retry count per downlink message (through MQTT or the rest API) after these changes have been released.
