### ISSUE TITLE
metadata.FromContext => metadata.FromIncomingContext

### ISSUE THREAD

**Issue by ghost** [brocaar/lora-app-server#170]
Hi,

Seems to me that in ~/go/src/github.com/brocaar/lora-app-server/internal/api/auth/auth.go your are using metadata.FromContext which is a deprecated function. You'd better use metadata.FromIncomingContext.

**Comment by brocaar** [comment]
Would you mind creating a pull-request for that? :-)

**Comment by pmiam999** [comment]
#171
