### ISSUE TITLE
Organization admin user cannot get organization applications

### ISSUE THREAD

**Issue by muka** [brocaar/lora-app-server#179]
From UI an user can be admin of an organization and create applications. Those are not listed then in the overview for the org admin, but show up for the global admin.

The relevant API call is `/api/applications?organizationID=5&limit=20&offset=0` which point respectively to
- https://github.com/brocaar/lora-app-server/blob/master/internal/api/application.go#L158
- https://github.com/brocaar/lora-app-server/blob/master/internal/storage/application.go#L160

**Comment by brocaar** [comment]
Could you post some screenshots? I'm not sure if I fully understand the issue.

**Comment by brocaar** [comment]
I just created an application as an "org admin". After creating this app, I can see it in the list of applications for this organization.

**Comment by muka** [comment]
Hi @brocaar, you can reproduce easily:

1. login as global admin, create org, create app, create org admin
2. login as org admin, no apps available
3. as global admin add org admin to app users
4. org admin view the app in the list

Seems there is a kind of "ownership" enforcement on apps, may it be the case?

Thanks

**Comment by brocaar** [comment]
Are you using the latest LoRa App Server / LoRa Server version? https://forum.loraserver.io/t/release-lora-server-0-22-0-lora-app-server-0-14-x-read-carefully/350

**Comment by muka** [comment]
No you are right, I miss the release notes.. I am still somewhere back in time (`0.13.1-1-g469930b`)

I will try again once up to 0.14, closing the issue I will reopen if still apply.

Thank you

**Comment by muka** [comment]
Tested with last tag (~0.14) and all works fine. Great work!
