### ISSUE TITLE
ability to move nodes/applications

### ISSUE THREAD

**Issue by mihaispataru** [brocaar/lora-app-server#181]
**Is this a bug or a feature request?**

Feature

**What did you expect?**

1. Possibility to move nodes from an application to another as admin or as user from an organization
2. Possibility to move applications with nodes from an organization to another as admin.

**Comment by brocaar** [comment]
I'm not sure if this is worth the complexity. There is more complexity than just changing the foreign-keys. Devices have a dependency on a device-profile and applications on a service-profile. The service-profile, device-profile and device **must** be provisioned on the same network-server.

**Comment by brocaar** [comment]
This is possible using the API, see: https://github.com/brocaar/lora-app-server/blob/master/api/device.proto#L139.

Given the complexity of validation, I do not have plans to support this in the web-interface.
