### ISSUE TITLE
Dreaded TLS handshake error (appserver)

### ISSUE THREAD

**Issue by hpcdan** [brocaar/lora-app-server#185]
I seem to have things working (I'm a newbie to LoRaWAN) except for the GUI.  When I try to connect (via https://localhost:8080).  I am using the version of the appserver pulled from docker.  I am assuming that it (based on the Dockerfile) is building the TLS certs in /etc/lora-app-server/certs.  Is that correct?

appserver_1      | time="2017-12-01T17:26:17Z" level=info msg="migrations applied" count=21 
appserver_1      | time="2017-12-01T17:26:17Z" level=info msg="starting application-server api" bind="0.0.0.0:8001" ca-cert= tls-cert= tls-key= 
appserver_1      | time="2017-12-01T17:26:17Z" level=info msg="starting join-server api" bind="0.0.0.0:8003" ca_cert= tls_cert= tls_key= 
appserver_1      | time="2017-12-01T17:26:17Z" level=info msg="starting client api server" bind="0.0.0.0:8080" tls-cert="/etc/lora-app-server/certs/http.pem" tls-key="/etc/lora-app-server/certs/http-key.pem" 
appserver_1      | time="2017-12-01T17:26:17Z" level=info msg="registering rest api handler and documentation endpoint" path="/api" 

 I always get the following errors:

(a) in the GUI, adding a network server

**Error rpc error: code = Unavailable desc = transport: write tcp 127.0.0.1:52762->127.0.0.1:8080: write: broken pipe (code: 2)**

(b) and in the log file

**appserver_1      | 2017/12/01 17:23:40 http: TLS handshake error from 127.0.0.1:54474: tls: first record does not look like a TLS handshake
appserver_1      | time="2017-12-01T17:23:40Z" level=info msg="transport: http2Client.notifyError got notified that the client transport was broken read tcp 127.0.0.1:54474->127.0.0.1:8080: read: connection reset by peer."**

**Comment by brocaar** [comment]
I think this has been solved already, hasn't it (in the forum)? Could you close the issue if so?
