### ISSUE TITLE
example compile problem

### ISSUE THREAD

**Issue by artuguy** [brocaar/lora-app-server#194]
Hi, Dear:

     I am compile the example from this web page https://docs.loraserver.io/lora-app-server/integrate/grpc/.  it is as below:

package main

import (
	"context"
	"log"

	"github.com/brocaar/lora-app-server/api"
	"google.golang.org/grpc"
)

func main() {
	// allow insecure / non-tls connections
	grpcOpts := []grpc.DialOption{
		grpc.WithInsecure(),
	}

	// connect to lora-app-server
	asConn, err := grpc.Dial("localhost:8080", grpcOpts...)
	if err != nil {
		log.Fatal(err)
	}

	// create a new node
	nodeAPI := api.NewNodeClient(asConn)
	_, err = nodeAPI.Create(context.Background(), &api.CreateNodeRequest{
		DevEUI:                 "0101010101010101",
		AppEUI:                 "0202020202020202",
		AppKey:                 "03030303030303030303030303030303",
		ApplicationID:          1,
		UseApplicationSettings: true,
	})
	if err != nil {
		log.Fatal(err)
	}
}
     when i type  "go build", on ubuntu ,  it reply:

 cannot use asConn (type *"google.golang.org/grpc".ClientConn) as type *"github.com/brocaar/lora-app-server/vendor/google.golang.org/grpc".ClientConn in argument to api.NewDeviceClient

I am a newer in golang,  what's wrong with it?
thanks

**Comment by brocaar** [comment]
This is a vendoring issue. As this is not a bug or feature request, please lets discuss this at https://forum.loraserver.io as the answer might be useful to others.
