### ISSUE TITLE
Select gateway for data sending

### ISSUE THREAD

**Issue by x0y1z2** [brocaar/lora-app-server#195]
I have one gateway with 8 channel and one simple gateway with 1 channel. I want to use only simple gateway for sending data, and 8-channel gateway for receiving. Because, when gateway send data, it can not receive it.

**Comment by brocaar** [comment]
I think this is technically not possible (for Class-A). For the downlink LoRa Server uses an internal timestamp provided by the receiving gateway. Only this gateway knows what this timestamp means and therefore the downlink must go through one of the gateways which received the uplink.
