### ISSUE TITLE
Error invalid channel (code:3)

### ISSUE THREAD

**Issue by bramkennis** [brocaar/lora-app-server#197]
### Is this a bug or a feature request?
Bug?

### What did you expect?
Correct way of adding extra channels.

### What happened?
configuring extra channels

### What version are your using?
Last versions

### How can your issue be reproduced?
adding channel 3,4,5,6,7 and hit submit.

### Could you share your log output?
![error2](https://user-images.githubusercontent.com/25924594/34814990-f291196e-f6af-11e7-9c63-cf5366dd93ea.png)
![error1](https://user-images.githubusercontent.com/25924594/34814993-f65299a6-f6af-11e7-8c16-e5f56c71c7c7.png)

**Comment by brocaar** [comment]
For EU the only channels that are defined by the LoRaWAN Regional Parameters are 0, 1, 2. The rest are the extra channels which you already entered below.

**Comment by bramkennis** [comment]
Ok great, so now i just need to install the lora-channel-manager on the multitech gateways to read and update the config file?

**Comment by brocaar** [comment]
correct
