### ISSUE TITLE
About application payload

### ISSUE THREAD

**Issue by ktsakos** [brocaar/lora-app-server#199]
I have a sensor that transmits LoRa packets.
I get all packages decrypted information and i see that my frame payload has values like these 099163 or 45C664. This sensor takes temperature and humidity measurements. But from the frame payload how should i read the information which contains to understand the measurements?

**Comment by brocaar** [comment]
Without information how the temp. and hum. are encoded, you can't decode it. Please discuss this further at https://forum.loraserver.io :-)
