### ISSUE TITLE
common.GatewayPingDR == 0 should be a valid value

### ISSUE THREAD

**Issue by krippendorf** [brocaar/lora-app-server#203]
Isn't data rate 0 a valid value for GatewayPingDR / gw-ping-dr

Seel https://github.com/brocaar/lora-app-server/blob/e5b3c3c40f6914c0ad661e5c5efedfe257c80648/cmd/lora-app-server/main.go#L279

**Comment by brocaar** [comment]
You're right, `dr=0` should be valid. I think it would be best to remove the `GatewayPingDR` check, as it defaults to `0`. Would you like to create a pull request?

**Comment by krippendorf** [comment]
Thx, will create PR  tonight :-)

**Comment by brocaar** [comment]
This has been fixed & merged :-)
