### ISSUE TITLE
Add some way to manage non-backward-compatible API changes

### ISSUE THREAD

**Issue by jcampanell-cablelabs** [brocaar/lora-app-server#206]
If an organization is using the REST API of lora-app-server, and the server is updated to a new incompatible API version, the client applications have almost no way to tell that this has happened and be able to manage the change gracefully.  This can happen pretty easily even on a server you have direct control over.  In our case, we run an Ubuntu server and are using the apt system to manage upgrades.  It would be pretty easy to miss that an _apt update/apt upgrade_ includes a changed lora-app-server that has an incompatible API.  And actually, you wouldn't even know the API is incompatible before it gets installed.

A couple of possible solutions:

1. Have a way to get the lora-app-server version number from the API.  This would allow us to verify we are working with a new server version at runtime, and at least throw out a warning.  

Benefits: simple to implement.  
Drawbacks: can't tell if the new code version has a compatible API until you run with it

2. In addition to (1), include an API version number, with major version changes indicating non-backward-compatible changes to the API.

Benefits: Not as easy to implement as (1), but still pretty easy.
Drawbacks:  Another version number to manage.  Can't tell the API is incompatible until you run with it.

3. Include an API version number in the URL, and have any updates to the code support the old API.  For example, when the change was made to support deviceProfiles, suppose a prior /api/V1/... API existed.  The lora-app-server *could* have been updated to add the newer API as V2, but the V1 API could still exist, handling matching new device settings to existing profiles, or creating new profiles if needed.  Or, even if the V1 API was removed as "no longer supported", making all calls return 404, it's easier for us managing client code to realize what the issue is, and that we have to update our code to support V2.

Benefits: Very easy for client code as no change needs to be immediately made unless the old version API is retired.
Drawbacks:  More difficult to manage the code.  Not obvious (via code) that new API is even available.  

I recommend a combination of 2 and 3.  2 tells us we should at least be thinking "upgrade", but 3 keeps backward compatibility available.  In this case, for 2, rather than giving the "latest" API version, gives an array of supported API versions, most recent first.

**Comment by brocaar** [comment]
This is now handled by providing one repository per major version and making all major versions compatible :-) See also: https://forum.loraserver.io/t/repository-changes-road-towards-1-0-0/1380.
