### ISSUE TITLE
Decode cayenne formated frame payload

### ISSUE THREAD

**Issue by ktsakos** [brocaar/lora-app-server#208]
How can i configure the service in order to decode the phypayload as low power cayenne payload? 
On the UI i don't see this setting!
Maybe have i an older version of the service?
How could i update it?

**Comment by brocaar** [comment]
See 0.16.0 release; https://docs.loraserver.io/lora-app-server/overview/changelog/

**Comment by ktsakos** [comment]
I have version 0.13.1
I have to make the same procedure to install the latest version or there is a command i should execute?
