### ISSUE TITLE
Upgrade to the latest version of lora-app-server

### ISSUE THREAD

**Issue by ktsakos** [brocaar/lora-app-server#210]
I have version 0.13.1
I have to make the same procedure to install the latest version or is there a command i should execute avoiding to delete something?

**Comment by brocaar** [comment]
Please stop using GitHub issues for support questions: https://forum.loraserver.io/t/how-to-upgrade-to-new-versions-of-lora-server-and-lora-app-server/213

**Comment by ktsakos** [comment]
I ran  sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 1CE2AFD36DBCCA00 after sudo apt-get update . Then ran sudo apt-get dist-upgrade loraserver lora-app-server.
