### ISSUE TITLE
json object from decode() function

### ISSUE THREAD

**Issue by espuser** [brocaar/lora-app-server#211]
### What did you expect?
a valid output every time
### What happened?
in average every fifth telegram produce {object: null} in the mqtt output
### What version are your using?
Latest version, downloaded two days ago for Debian jessie
### How can your issue be reproduced?
mosquitto_sub -v -t 'application/#'
### Could you share your log output?

```
application/1/node/001aba3b28568620/rx {"applicationID":"1","applicationName":"PAC4200","deviceName":"rn2483dev2","devEUI":"001aba3b28568620","rxInfo":[{"mac":"aa555a0000000101","time":"2018-02-03T19:38:08.632167Z","rssi":-19,"loRaSNR":9,"name":"IS880A","latitude":51,"longitude":9,"altitude":235}],"txInfo":{"frequency":868300000,"dataRate":{"modulation":"LORA","bandwidth":125,"spreadFactor":7},"adr":false,"codeRate":"4/5"},"fCnt":273,"fPort":3,"data":"YnRmQwAAAAAAAAAA","object":{"voltageL1":230.45462036132812,"voltageL2":0,"voltageL3":0}}
application/1/node/001aba3b28568620/rx {"applicationID":"1","applicationName":"PAC4200","deviceName":"rn2483dev2","devEUI":"001aba3b28568620","rxInfo":[{"mac":"aa555a0000000101","time":"2018-02-03T19:38:40.814711Z","rssi":-20,"loRaSNR":8.5,"name":"IS880A","latitude":51,"longitude":9,"altitude":235}],"txInfo":{"frequency":868300000,"dataRate":{"modulation":"LORA","bandwidth":125,"spreadFactor":7},"adr":false,"codeRate":"4/5"},"fCnt":274,"fPort":3,"data":"fudmQwAAAAAAAAAA","object":null}
application/1/node/001aba3b28568620/rx {"applicationID":"1","applicationName":"PAC4200","deviceName":"rn2483dev2","devEUI":"001aba3b28568620","rxInfo":[{"mac":"aa555a0000000101","time":"2018-02-03T19:39:12.986757Z","rssi":-19,"loRaSNR":9,"name":"IS880A","latitude":51,"longitude":9,"altitude":235}],"txInfo":{"frequency":867700000,"dataRate":{"modulation":"LORA","bandwidth":125,"spreadFactor":7},"adr":false,"codeRate":"4/5"},"fCnt":275,"fPort":3,"data":"NP5mQwAAAAAAAAAA","object":{"voltageL1":230.99298095703125,"voltageL2":0,"voltageL3":0}}
application/1/node/001aba3b28568620/rx {"applicationID":"1","applicationName":"PAC4200","deviceName":"rn2483dev2","devEUI":"001aba3b28568620","rxInfo":[{"mac":"aa555a0000000101","time":"2018-02-03T19:39:45.163077Z","rssi":-22,"loRaSNR":9.8,"name":"IS880A","latitude":51,"longitude":9,"altitude":235}],"txInfo":{"frequency":867100000,"dataRate":{"modulation":"LORA","bandwidth":125,"spreadFactor":7},"adr":false,"codeRate":"4/5"},"fCnt":276,"fPort":3,"data":"WwJnQwAAAAAAAAAA","object":{"voltageL1":231.0092010498047,"voltageL2":0,"voltageL3":0}}
```

**Comment by espuser** [comment]
when object is null, the time field in application/x/node/xxxxxxxx/rx  array rxInfo is also missing

**Comment by brocaar** [comment]
Could you please provide your JS function?

**Comment by espuser** [comment]
Hi,
I use port == 3, I get three floats  (voltage L1, L2, L3 of my home meter PAC4200) IEEE754 type, each 4 byte long

function Decoder(bytes, port) {
  if(port === 2) {
    var accelx = byte2signed(bytes[0], bytes[1]);
    var accely = byte2signed(bytes[2], bytes[3]);
    var accelz = byte2signed(bytes[4], bytes[5]);
    var gyrox = byte2signed(bytes[6], bytes[7]);
    var gyroy = byte2signed(bytes[8], bytes[9]);
    var gyroz = byte2signed(bytes[10], bytes[11]);
    return {
      accelX: accelx,
      accelY: accely,
      accelZ: accelz,
      gyroX: gyrox,
      gyroY: gyroy,
      gyroZ: gyroz
    };
  } else if(port === 3) {
    var voltagel1 = ieee32ToFloat(bytes[0] | (bytes[1] << 8) | (bytes[2] << 16) | (bytes[3] << 24));
    var voltagel2 = ieee32ToFloat(bytes[4] | (bytes[5] << 8) | (bytes[6] << 16) | (bytes[7] << 24));
    var voltagel3 = ieee32ToFloat(bytes[8] | (bytes[9] << 8) | (bytes[10] << 16) | (bytes[11] << 24));
    // var currentl1 = ieee32ToFloat(bytes[0] | (bytes[1] << 8) | (bytes[2] << 16) | (bytes[3] << 24));
    // var currentl2 = ieee32ToFloat(bytes[0] | (bytes[1] << 8) | (bytes[2] << 16) | (bytes[3] << 24));
    // var currentl3 = ieee32ToFloat(bytes[0] | (bytes[1] << 8) | (bytes[2] << 16) | (bytes[3] << 24));
    return {
      voltageL1: voltagel1,
      voltageL2: voltagel2,
      voltageL3: voltagel3,
      // currentL1: currentl1,
      // currentL2: currentl2,
      // currentL3: currentl3
    };
  } else {
    return {
      Errorcode: "port " + port + "not supported yet"
    };
  }
}

function byte2signed(byteB, byteA) {
  var sign = byteA & (1 << 7);
  var result = (((byteA & 0xFF) << 8) | (byteB & 0xFF));
  if (sign) {
    result = 0xFFFF0000 | result; // fill in most significant bits with 1's
  }
  return result;
}

function ieee32ToFloat(intval) {
  var fval = 0.0;
  var x; //exponent
  var m; //mantissa
  var s; //sign
  s = (intval & 0x80000000)?-1:1;
  x = ((intval >> 23) & 0xFF);
  m = (intval & 0x7FFFFF);
  switch(x) {
    case 0:
    //zero, do nothing, ignore negative zero and subnormals
    break;
    case 0xFF:
      if (m) fval = NaN;
      else if (s > 0) fval = Number.POSITIVE_INFINITY;
      else fval = Number.NEGATIVE_INFINITY;
      break;
    default:
      x -= 127;
      m += 0x800000;
      fval = s * (m / 8388608.0) * Math.pow(2, x);
      break;
  }
  return fval;
}

BR
Bernd

**Comment by fifthaxe** [comment]
Expected argument name is **fPort** not **port**.

**Comment by brocaar** [comment]
@espuser do you still have this issue? I just tested your JS code against the payload resulting in an empty object, and from a JS console it does return an object. So nothing wrong with your JS code.

What could be an issue is that the JS VM is only allowed to run 10 ms. I hope your calculation does not take 10ms, but you could try to increase that value: https://github.com/brocaar/lora-app-server/blob/master/internal/codec/custom_js.go#L14.

**Comment by JimCAtSentosa** [comment]
Hey, saw this in passing.  Is it possible "NaN" is not defined in the context that this is running under?  Maybe try Number.NaN?

**Comment by brocaar** [comment]
In the above commit, I'm now logging codec errors as device error events. This means they will be visible in the MQTT `..../error` topic and can also be inspected in the web-interface under the **live event logs** tab (device).
