### ISSUE TITLE
Reset Frame counter for ABP devices

### ISSUE THREAD

**Issue by espuser** [brocaar/lora-app-server#213]
### Is this a bug or a feature request?
I know that the frame counter is part of a security feature. For development it is heavy to wait until the frame counter is above the last count before Device reset.

### What did you expect?
a button to reset the frame counter
### What version are your using?
latest version downloaded 3 days ago for Debian jessie

**Comment by brocaar** [comment]
You can either use the relax frame-counter mode (which is not secure) or re-activate your device (ABP) with the same keys and frame-counters to `0` (which isn't secure either).

**Comment by ayodhyadhameesha** [comment]
Hello brocaar,
Can you help me to reactivate the device automatically, like from a code or something.
