### ISSUE TITLE
Unable to create a network server

### ISSUE THREAD

**Issue by dpmendes** [brocaar/lora-app-server#214]
I believe this bug is probably a misconfiguration I made somewhere, but I can't find a way to fix it.
On the network servers screen, I add a network-server name and a network-server server (localhost:8000). All the other fields are blank. When I click "submit", I receive the error "Error context deadline exceeded (code: 2)", as shown next:

![image](https://user-images.githubusercontent.com/12697686/35967539-48ddc4d0-0ca8-11e8-8b0b-7c5450511092.png)

I'm running lora-app-server version 0.17.1.
Everything else is working fine since I can connect an end device to my gateway and see its data on a TTN app server.

Regards.

**Comment by brocaar** [comment]
The forum is a better place for support questions: https://forum.loraserver.io/t/can-not-register-network-server/407.

**Comment by dpmendes** [comment]
Thanks.

Sorry for posting on the wrong place.
