### ISSUE TITLE
add network-server issue

### ISSUE THREAD

**Issue by guhongyeying** [brocaar/lora-app-server#215]
### Is this a bug or a feature request?
I will is  a feature request

### What did you expect?
how can i deal with。
### What happened?
Certificates for LoRa App Server to LoRa Server connection   add network server  fail on  lora-app-server UI
### What version are your using?
loraserver/lora-app-server       latest
### How can your issue be reproduced?
when i add network-server
### Could you share your log output?
time="2018-02-09T02:29:01Z" level=error msg="finished unary call with code Unknown" error="rpc error: code = Unknown desc = tls: failed to find any PEM data in certificate input" grpc.code=Unknown grpc.method=Create grpc.service=api.NetworkServer grpc.start_time="2018-02-09T02:29:01Z" grpc.time_ms=78.684 peer.address="127.0.0.1:37876" span.kind=server system=grpc

**Comment by brocaar** [comment]
Please use the forum for support: https://forum.loraserver.io :-)
