### ISSUE TITLE
regional parameters RU864_870

### ISSUE THREAD

**Issue by VahrushevSA** [brocaar/lora-app-server#219]
Hello Brocaar!
I ask to compile a new build lora-app-server
[LoRaWAN Regional Parameters v1.1rB - Final.pdf](https://github.com/brocaar/lora-app-server/files/1787964/LoRaWAN.Regional.Parameters.v1.1rB.-.Final.pdf)
 on the basis of regional parameters RU864_870

**Comment by brocaar** [comment]
This has already been released.
