### ISSUE TITLE
Why it print "jwt parse error: token is expired by 65h1m50s" when I start running lora-app-server

### ISSUE THREAD

**Issue by WuHaiBinkenny** [brocaar/lora-app-server#223]
### Is this a bug or a feature request?
bug?
### What happened?
when I start running lora-app-server, it print jwt parse error
### What version are your using?
0.18.2
### How can your issue be reproduced?
when it's start
### Could you share your log output?
INFO[0000] starting LoRa App Server                      docs="https://docs.loraserver.io/" version=0.18.2
INFO[0000] connecting to postgresql                     
INFO[0000] setup redis connection pool                  
INFO[0000] handler/mqtt: TLS config is empty            
INFO[0000] handler/mqtt: connecting to mqtt broker       server="tcp://localhost:1883"
INFO[0000] applying database migrations                 
INFO[0000] handler/mqtt: connected to mqtt broker       
INFO[0000] handler/mqtt: subscribing to tx topic         qos=0 topic=application/+/node/+/tx
INFO[0000] migrations applied                            count=0
INFO[0000] starting application-server api               bind="0.0.0.0:8001" ca-cert= tls-cert= tls-key=
INFO[0000] starting join-server api                      bind="0.0.0.0:8003" ca_cert= tls_cert= tls_key=
INFO[0000] starting client api server                    bind="0.0.0.0:8080" tls-cert=/etc/lora-app-server/certs/http.pem tls-key=/etc/lora-app-server/certs/http-key.pem
INFO[0000] registering rest api handler and documentation endpoint  path=/api
INFO[0000] finished streaming call with code Unauthenticated  error="rpc error: code = Unauthenticated desc = authentication failed: jwt parse error: token is expired by 65h1m50s" grpc.code=Unauthenticated grpc.method=StreamFrameLogs grpc.service=api.Gateway grpc.start_time="2018-03-20T10:08:10+08:00" grpc.time_ms=0.437 peer.address="127.0.0.1:44022" span.kind=server system=grpc
INFO[0000] finished streaming call with code Unauthenticated  error="rpc error: code = Unauthenticated desc = authentication failed: jwt parse error: token is expired by 65h1m50s" grpc.code=Unauthenticated grpc.method=StreamFrameLogs grpc.service=api.Device grpc.start_time="2018-03-20T10:08:10+08:00" grpc.time_ms=0.602 peer.address="127.0.0.1:44018" span.kind=server system=grpc
INFO[0000] finished streaming call with code Unauthenticated  error="rpc error: code = Unauthenticated desc = authentication failed: jwt parse error: token is expired by 65h1m50s" grpc.code=Unauthenticated grpc.method=StreamFrameLogs grpc.service=api.Gateway grpc.start_time="2018-03-20T10:08:10+08:00" grpc.time_ms=0.211 peer.address="127.0.0.1:44022" span.kind=server system=grpc
INFO[0003] finished streaming call with code Unauthenticated  error="rpc error: code = Unauthenticated desc = authentication failed: jwt parse error: token is expired by 65h1m52s" grpc.code=Unauthenticated grpc.method=StreamFrameLogs grpc.service=api.Device grpc.start_time="2018-03-20T10:08:12+08:00" grpc.time_ms=0.294 peer.address="127.0.0.1:44018" span.kind=server system=grpc
INFO[0003] finished streaming call with code Unauthenticated  error="rpc error: code = Unauthenticated desc = authentication failed: jwt parse error: token is expired by 65h1m53s" grpc.code=Unauthenticated grpc.method=StreamFrameLogs grpc.service=api.Device grpc.start_time="2018-03-20T10:08:13+08:00" grpc.time_ms=0.321 peer.address="127.0.0.1:44018" span.kind=server system=grpc
INFO[0004] finished streaming call with code Unauthenticated  error="rpc error: code = Unauthenticated desc = authentication failed: jwt parse error: token is expired by 65h1m54s" grpc.code=Unauthenticated grpc.method=StreamFrameLogs grpc.service=api.Gateway grpc.start_time="2018-03-20T10:08:14+08:00" grpc.time_ms=0.347 peer.address="127.0.0.1:44022" span.kind=server system=grpc
INFO[0004] finished streaming call with code Unauthenticated  error="rpc error: code = Unauthenticated desc = authentication failed: jwt parse error: token is expired by 65h1m54s" grpc.code=Unauthenticated grpc.method=StreamFrameLogs grpc.service=api.Device grpc.start_time="2018-03-20T10:08:14+08:00" grpc.time_ms=0.321 peer.address="127.0.0.1:44018" span.kind=server system=grpc

**Comment by brocaar** [comment]
I think the error is quite clear :-)

authentication failed: jwt parse error: **token is expired by 65h1m54s**
