### ISSUE TITLE
Discovery Enable Error

### ISSUE THREAD

**Issue by jvillamo** [brocaar/lora-app-server#226]
When I activate the discovery enable, the docker console pulls the following error, every second.

`postgresql_as_1 | ERROR: division by zero `
`postgresql_as_1 | STATEMENT:` 
`postgresql_as_1 | `
`select postgresql_as_1 | g.* postgresql_as_1 | from gateway g` 
`postgresql_as_1 | inner join network_server ns` 
`postgresql_as_1 | on ns.id = g.network_server_id `
`postgresql_as_1 | where postgresql_as_1 | ns.gateway_discovery_enabled = true `
`postgresql_as_1 | and g.ping = true `
`postgresql_as_1 | and (g.last_ping_sent_at is null or g.last_ping_sent_at <= (now() - (interval '24 hours' / ns.gateway_discovery_interval)))` 
`postgresql_as_1 | order by last_ping_sent_at `
`postgresql_as_1 | limit 1` 
`postgresql_as_1 | for update `
`appserver_1 | time="2018-03-27T15:52:37Z" level=error msg="send gateway ping error: get gateway for ping error: select error: pq: division by zero"`

**Comment by jvillamo** [comment]
When I activate the discovery enable, the docker console pulls the following error, every second.

`
postgresql_as_1  | ERROR:  division by zero
postgresql_as_1  | STATEMENT:  
postgresql_as_1  | 			select
postgresql_as_1  | 				g.*
postgresql_as_1  | 			from gateway g
postgresql_as_1  | 			inner join network_server ns
postgresql_as_1  | 				on ns.id = g.network_server_id
postgresql_as_1  | 			where
postgresql_as_1  | 				ns.gateway_discovery_enabled = true
postgresql_as_1  | 				and g.ping = true
postgresql_as_1  | 				and (g.last_ping_sent_at is null or g.last_ping_sent_at <= (now() - (interval '24 hours' / ns.gateway_discovery_interval)))
postgresql_as_1  | 			order by last_ping_sent_at
postgresql_as_1  | 			limit 1
postgresql_as_1  | 			for update
appserver_1      | time="2018-03-27T15:52:37Z" level=error msg="send gateway ping error: get gateway for ping error: select error: pq: division by zero"
`

**Comment by brocaar** [comment]
Thanks, that should have been raised a validation error when configuring. For now, please set the interval value at something larger than `0` :-)
