### ISSUE TITLE
0.19.0+ Upgrade instructions do not mention pg_trgm

### ISSUE THREAD

**Issue by sa-wilson** [brocaar/lora-app-server#227]
The upgrade notes on the releases page for 0.19.0/0.20.0 do not mention needing to enable the tgrm extension on the Postgres database.

The app server then crashes when attempting to load the migrations, but only has an error message on the first attempt. It could be quite easy for someone to miss that message and spend a long time trying to find why it's broken unless they check the install instructions.

EDIT: I did just notice that it is mentioned in the changelog on loraserver.io, but mentioning it on github is probably good for those of us that skim here

**Comment by brocaar** [comment]
Thanks! Has been fixed :-)
