### ISSUE TITLE
How to config DB table?

### ISSUE THREAD

**Issue by mybrand** [brocaar/lora-app-server#23]
![kakaotalk_20170220_205312006](https://cloud.githubusercontent.com/assets/1661904/23131198/7e2eba8c-f7cc-11e6-829d-8d7fcf03b289.png)

When I try to access with web browser, after setup lora-app-server I got code:13 error message.
If I want to access app-server page, how to configure DB setting?

**Comment by brocaar** [comment]
Please see the `--db-automigrate` config flag: https://docs.loraserver.io/lora-app-server/configuration/. When this flag is given, LoRa App Server will upgrade your database schema on start (see also: https://github.com/brocaar/lora-app-server/tree/master/migrations). So this not only creates all tables, but will perform schema updates when upgrading LoRa App Server.

**Comment by mybrand** [comment]
--db-automigrate option is work!!
Thanks.
