### ISSUE TITLE
IP information

### ISSUE THREAD

**Issue by shepiloff** [brocaar/lora-app-server#231]
### Is this a bug or a feature request?
Feature
### What did you expect?
Display Gateway IP information  in "Gateway details"  tab. 
### What version are your using?
Loraserver v0.26.0 / Lora App Server v0.20.0

**Comment by brocaar** [comment]
Could you please create this feature-request here: https://github.com/brocaar/lora-gateway-bridge/issues? This is the component that could be aware of the gateway IP.
