### ISSUE TITLE
Listing Device Queue Item API result missing reference value.

### ISSUE THREAD

**Issue by toseki** [brocaar/lora-app-server#233]
### Is this a bug or a feature request?
bug

### What did you expect?
I expected properly confirming "reference" value via downlink queue api.

### What happened?
Listing DownlinkQueueItem API "reference" value always missing. (/api/devices/{devEUI}/queue)

### What version are your using?
0.20.1

### How can your issue be reproduced?
example) posting downlink queue item.
`
{
  "confirmed": true,
  "data": "AP8RIjNEVWZ3iJk=",
  "devEUI": "1234567890abcdef",
  "fPort": 1,
  "reference": "test"
}
`

example) listing downlink queue item response.
```
{
  "items": [
    {
      "devEUI": "1234567890abcdef",
      "reference": "",  <----- missing reference strings.
      "confirmed": true,
      "fPort": 1,
      "data": "AP8RIjNEVWZ3iJk=",
      "fCnt": 6
    }
  ]
}
```

*seems to be queueItemsResp.Items and NS device_queue table not including "reference" values.

https://github.com/brocaar/lora-app-server/blob/a5e0304da22f466c32ac292ef7e4086813e730f2/internal/api/device_queue.go#L154-L172

https://github.com/brocaar/loraserver/blob/66f2a4bc93758fea4a7c2255cfe6d69363a313a3/internal/storage/device_queue.go#L231

**Comment by brocaar** [comment]
This will be handled differently and be fixed in upcoming release :-)
