### ISSUE TITLE
make api fails with undefined: proto.InternalMessageInfo

### ISSUE THREAD

**Issue by urbie-mk2** [brocaar/lora-app-server#234]
### Is this a bug or a feature request?
bug / help
### What did you expect?
compiled binary
### What happened?
error message occurs: api/application.pb.go:89:46: undefined: proto.InternalMessageInfo
### What version are your using?
master head
### How can your issue be reproduced?

1. git clone  lora-app-server (this repo)
2. make requirements && make ui-requirements && make api && make
-> error: `api/application.pb.go:89:46: undefined: proto.InternalMessageInfo`

### Could you share your log output?
`api/application.pb.go:89:46: undefined: proto.InternalMessageInfo`

make requirements downloads a complete protobuf package in go/src/.. and one incomplete protobuf package in lora-app-server/vendor/...

When I delete the protobuf package in vendor lora-app-server compiles. I could not find out from the logs where the vendor protobuf version is coming from but I would like to know and why it is incomplete.

sidenote: lora-app-server compiles if make api is never run before make.

[make-requirements.log](https://github.com/brocaar/lora-app-server/files/1973872/make-requirements.log)

**Comment by brocaar** [comment]
Could you also confirm that these steps are failing with the provided Docker development image? See also: https://www.loraserver.io/lora-app-server/community/source/

**Comment by urbie-mk2** [comment]
Sorry, lunch break.

It failed as well: 
[lora-app-server-docker-compose.log](https://github.com/brocaar/lora-app-server/files/1974287/lora-app-server-docker-compose.log)

**Comment by brocaar** [comment]
This should be fixed. Basically the gRPC generator (newer version) was generating code unsupported by the protobuf library (older version). I've updated the protobuf dependency version.
