### ISSUE TITLE
2 lora server for app-server

### ISSUE THREAD

**Issue by Akior** [brocaar/lora-app-server#236]
### Is this a bug or a feature request?
bug
### What did you expect?
Gateway with different network lora-server profile, will connect only for it's servers
### What happened?
Packet received all servers
### What version are your using?
/usr/bin/loraserver version
0.26.1
/usr/bin/lora-app-server version
0.20.1
### How can your issue be reproduced?
Create 2 lora-server on the same machine. 
Add 2 server to app-server
1.
Add gateway for second network server
Look for packet on first network server:
Or
2.
Add gateway for first network server
Look for packet on second network server

### Could you share your log output?
1.
май 07 16:24:10 loraservers loraserver[26374]: time="2018-05-07T16:24:10+03:00" level=info msg="backend/gateway: rx packet received"
май 07 16:24:11 loraservers loraserver[26374]: time="2018-05-07T16:24:11+03:00" level=info msg="packet(s) collected" dev_eui=0016c00000101632 gw_count=1 gw_macs=b827ebfffe3d6d5a mtype=JoinRequest
май 07 16:24:11 loraservers loraserver[26374]: time="2018-05-07T16:24:11+03:00" level=error msg="processing rx packet error: get device error: object does not exist" data_base64="AAEBAAAAwBYAMhYQAADAFgA+o2a57VA="
2.
WARN[0151] get gateways for macs error: expected 1 gateways, got 0  macs="[b827ebfffe346091]"
WARN[0154] new_channel request not acknowledged          channel=8 channel_frequency_ok=true data_rate_range_ok=false frequency=868300000 max_dr=5 min_dr=0
WARN[0154] new_channel request not acknowledged          channel=9 channel_frequency_ok=true data_rate_range_ok=false frequency=868800000 max_dr=5 min_dr=0
WARN[0154] get gateways for macs error: expected 1 gateways, got 0  macs="[b827ebfffe346091]"

**Comment by brocaar** [comment]
This is not a bug. LoRa Server will receive and process data from the configured MQTT broker. When both LoRa Server instances share the same MQTT configuration, they will see the same data. When setting up different clusters, you could configure different MQTT prefixes. This is configurable in the LoRa Gateway Bridge and LoRa Server configuration files.
