### ISSUE TITLE
InfluxDB integration

### ISSUE THREAD

**Issue by blange48** [brocaar/lora-app-server#238]
### Is this a bug or a feature request?
Feature

### What did you expect?
Thanks, for your amazing job with the influxes integration. You have add to loraserver a great feature. 
In a past and in order to visualise data, I have do the same thing, by creating a simple mutt wrapper to push data ton influx.

To improve your system, It is can be interesting to add RSSi and SNR to the device uplink. With this data, it will be possible to put rosi and sir in grafana.

Another interesting feature is the sequence number, it can be interesting to add it to the device uplink, in order to understand what happen.  (and also prepare future features)   

Finally, I have also plug a sniffer on the gateway topic, and also plug it into influxDB. This component can be useful to integrate in roder to have a clear understanding of large network. 

### What version are your using?
Last one

**Comment by sarunyu** [comment]
I want it too :)

**Comment by brocaar** [comment]
This has been implemented in the above commit :)
