### ISSUE TITLE
Database connection fails if password includes '?'

### ISSUE THREAD

**Issue by albtrentadue** [brocaar/lora-app-server#239]
I think this is an undesired behavior: I modified the password for loraserver_as postgresql user into: '278wbHH?o1'
After this, app-server will not startup properly with message in the log:

giu 01 14:43:47 iotdev2809 lora-app-server[5354]: time="2018-06-01T14:43:47+02:00" level=error msg="ping database error, will retry in 2s: dial tcp: address tcp/278wbHH: unknown port"

It took some time to understand. After changing '?' into a plain character, app-server would start OK.
It is not obvious that '?' is not accepted, should be accepted or docs should inform not to use it.

I am using version 1.0.1

**Comment by brocaar** [comment]
Maybe this could be extra documented, but as you can see in the example it splits the URL from the `sslmode` argument:

> postgres://user:password@hostname/database?sslmode=disable

If you think this could be documented better, feel free to create a pull-request :-)

**Comment by albtrentadue** [comment]
Ok, I will think about how to improve the docs and contribute.
Still I believe that this is a weakness in code.
By looking into the line in the log file generated: "address _tcp/278wbHH_: unknown port", it can be seen that the '?' in my password has caused wrong DSN parsing.

**Comment by brocaar** [comment]
The string itself is handled by the https://github.com/lib/pq driver. When you think it is a weakness in the code, I recommend creating a ticket there :-)

**Comment by albtrentadue** [comment]
Fair enough. Thanks.
