### ISSUE TITLE
Extra downlink acknowledgement is coming while sending downlink packet to End device in class C 

### ISSUE THREAD

**Issue by Richaagarwalrn** [brocaar/lora-app-server#241]
### Is this a bug or a feature request?
bug
### What did you expect?
Only downlink packet should be transmitted to End device.
### What happened?
Whenever we are sending confirmed downlink packet in Class C one extra downlink acknowledgement also get transmitted in RX2 window(ISM Band).
### What version are your using?
lora-app-server version 1.0.1 
loraserver 1.0.0.1-g33338792
lora-gateway-bridge 2.4.1.2-gc4d9f50

### How can your issue be reproduced?
Send confirmed downlink data from Server to End device
### Could you share your log output?

![loraserver_bug](https://user-images.githubusercontent.com/23451960/41217875-e6a04b5a-6d76-11e8-9551-6738b1bc6aaf.png)

**Comment by brocaar** [comment]
Could you download and attach the JSON log output (click the download button in the same window)?

**Comment by brocaar** [comment]
I'm closing this issue as no further details are provided. Probably this is a mac-command related issue (e.g. device does not acknowledge mac-command and LoRa Server re-sends these during uplink).
