### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9d389c]

### ISSUE THREAD

**Issue by wssq** [brocaar/lora-app-server#247]

**Comment by wssq** [comment]
yes,I did.
I have done the following:

> cd /usr/local/go/src/github.com/brocaar/lora-app-server/cmd/lora-app-server

> go build main.go

> ./main

**Comment by brocaar** [comment]
Please see https://www.loraserver.io/lora-app-server/community/source/ and https://forum.loraserver.io/t/compiling-the-lora-app-server-source-code/643.
