### ISSUE TITLE
cannot find package "github.com/brocaar/lora-app-server/internal/migrations"

### ISSUE THREAD

**Issue by david1372** [brocaar/lora-app-server#248]
Hi.
I have following problem when I use `go build main.go`

> cmd\lora-app-server\cmd\root_run.go:39:2: cannot find package "github.com/brocaar/lora-app-server/internal/migrations" in any of:
> 	C:\Go\src\vendor\github.com\brocaar\lora-app-server\internal\migrations (vendor tree)
> 	C:\Go\src\github.com\brocaar\lora-app-server\internal\migrations (from $GOROOT)
> 	C:\Users\MRT\go\src\github.com\brocaar\lora-app-server\internal\migrations (from $GOPATH)
> cmd\lora-app-server\cmd\root_run.go:41:2: cannot find package "github.com/brocaar/lora-app-server/internal/static" in any of:
> 	C:\Go\src\vendor\github.com\brocaar\lora-app-server\internal\static (vendor tree)
> 	C:\Go\src\github.com\brocaar\lora-app-server\internal\static (from $GOROOT)
> 	C:\Users\MRT\go\src\github.com\brocaar\lora-app-server\internal\static (from $GOPATH)

when I change imports to 

> "github.com\brocaar\lora-app-server\migrations"
> "github.com\brocaar\lora-app-server\static"

I get following error:

> cmd\lora-app-server\cmd\root_run.go:39:2: no Go files in C:\Go\src\github.com\brocaar\lora-app-server\migrations
> cmd\lora-app-server\cmd\root_run.go:41:2: no Go files in C:\Go\src\github.com\brocaar\lora-app-server\static

Should I commend all line that use `migrations` and `static`? Will I have problem in the future,If I commend them?

**Comment by brocaar** [comment]
Please see https://www.loraserver.io/lora-app-server/community/source/ and https://forum.loraserver.io/t/compiling-the-lora-app-server-source-code/643.
