### ISSUE TITLE
✗ unable to deduce repository and source type for "golang.org/x/crypto": unable to read metadata: unable to parse go-import metadata: XML syntax error on line 9: expected /> in element

### ISSUE THREAD

**Issue by david1372** [brocaar/lora-app-server#249]
Hi.
When I use `make requirements ui-requirements` based on https://www.loraserver.io/lora-app-server/community/source/
I have following error:

> eza@ubuntu:~/work/src/github.com/brocaar/lora-app-server$ make requirements ui-requirements
> Installing development tools
> The following issues were found in Gopkg.toml:
> 
>   ✗ unable to deduce repository and source type for "golang.org/x/crypto": unable to read metadata: unable to parse go-import metadata: XML syntax error on line 9: expected /> in element
>   ✗ unable to deduce repository and source type for "golang.org/x/net": unable to read metadata: unable to parse go-import metadata: XML syntax error on line 9: expected /> in element
>   ✗ unable to deduce repository and source type for "google.golang.org/genproto": unable to read metadata: unable to parse go-import metadata: XML syntax error on line 9: expected /> in element
>   ✗ unable to deduce repository and source type for "google.golang.org/grpc": unable to read metadata: unable to parse go-import metadata: XML syntax error on line 9: expected /> in element
> 
> ProjectRoot name validation failed
> Makefile:63: recipe for target 'requirements' failed
> make: *** [requirements] Error 1
> 
> 
>

**Comment by brocaar** [comment]
This looks like a network or proxy issue at your side. All these steps are executed each time on a github push and they work well: https://travis-ci.org/brocaar/lora-app-server.
