### ISSUE TITLE
Data not received with MQTT !!

### ISSUE THREAD

**Issue by AnisBH** [brocaar/lora-app-server#25]
Hi Brocaar :) , 

Please i have a problem, i can't receive data with MQTT , the device join network  OTAA without any problems then send data is successful but to see data with moquitto_sub  doesn't work :/  please where is exactly the problem? 

Thanks Brocaar :)

**Comment by AnisBH** [comment]
Hello :) , 

the problem that i'm using this command  [AppEUI = 70B3D57EF000391A ] :  
mosquitto_sub -t "application/70B3D57EF000391A/#" -v

but when i use this command : 
mosquitto_sub -v -t "application/#"

i receiv data , and i see as Application ID  => application/1/node/0004a30b001ae41e/rx {"applicationID":"1", ... 

Please , applicationID is not 70B3D57EF000391A ? why i receive "1" ?

**Comment by brocaar** [comment]
Note that `AppEUI` is not `ApplicationID`. I'll update the docs / UI to make this more clear.

Multiple nodes with different `AppEUI` values could still serve the same application / purpose (e.g. weather station). The `ApplicationID` matches the ID of the application that you created, before adding any nodes. See also the `/api/applications?limit=10` api endpoint :-)

**Comment by AnisBH** [comment]
Thanks broccar :) Thank you for your work and your efforts . 
Please clear us this point on the doc . 
Regards ,
