### ISSUE TITLE
FATA[0000] tls cert and tls key must be set for the external api 

### ISSUE THREAD

**Issue by david1372** [brocaar/lora-app-server#250]
Hi.
I have  an error in running  lora-app-server

> eza@ubuntu:~/work1/src/github.com/brocaar/lora-app-server/build$ ./lora-app-server 
> WARN[0000] No configuration file found, using defaults. See: https://www.loraserver.io/lora-app-server/install/config/ 
> INFO[0000] starting LoRa App Server                      docs="https://www.loraserver.io/" version=2.0.0-alpha.2-2-gd9c0628
> INFO[0000] connecting to postgresql                     
> INFO[0000] setup redis connection pool                  
> INFO[0000] handler/mqtt: TLS config is empty            
> INFO[0000] handler/mqtt: connecting to mqtt broker       server="tcp://localhost:1883"
> INFO[0000] applying database migrations                 
> INFO[0000] handler/mqtt: connected to mqtt broker       
> INFO[0000] handler/mqtt: subscribing to tx topic         qos=0 topic=application/+/device/+/tx
> INFO[0000] migrations applied                            count=0
> INFO[0000] starting application-server api               bind="0.0.0.0:8001" ca-cert= tls-cert= tls-key=
> INFO[0000] starting join-server api                      bind="0.0.0.0:8003" ca_cert= tls_cert= tls_key=
> FATA[0000] tls cert and tls key must be set for the external api 

I have changed root.go:

```
viper.SetDefault("postgresql.dsn", "postgres://loraserver_as:dbpassword@localhost/loraserver_as?sslmode=disable")
viper.SetDefault("application_server.external_api.tls_cert", "/etc/lora-app-server/certs/http.pem")
viper.SetDefault("application_server.external_api.tls_key", "/etc/lora-app-server/certs/http-key.pem")
viper.SetDefault("application_server.external_api.jwt_secret","password")
```

How can fix this?

**Comment by brocaar** [comment]
You should not make this change in `root.go`. Please see https://www.loraserver.io/lora-app-server/install/config/.

**Comment by DuyTran2626** [comment]
How can i fixed it. I had the same issues
