### ISSUE TITLE
 'GOOS' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by wsaq** [brocaar/lora-app-server#251]
Hello
I want to run lora-app-server in windows 10 and for this I use gnuwin32, But when I use  `make requirements ui-requirements `or `make build`, I have following error:

> "Generating combined Swagger JSON"
> 'GOOS' is not recognized as an internal or external command,
> operable program or batch file.
> make: *** [static/swagger/api.swagger.json] Error 1

**Comment by brocaar** [comment]
Using the provided Docker container for compiling should solve your issue: https://www.loraserver.io/lora-app-server/community/source/.
