### ISSUE TITLE
Gateway stats packet not present in frame logs

### ISSUE THREAD

**Issue by tomaql** [brocaar/lora-app-server#255]
### Is this a bug or a feature request?
Bug

### What did you expect?
In the live frame logs for the gateway, I would expect to see the gateway stats packets

### What happened?
Only tx/rx infro displayed

### What version are your using?
2.0.0

### How can your issue be reproduced?
Looking at the gateway frame logs

**Comment by brocaar** [comment]
The stats are indeed not displayed as the purpose of the tab is to show LoRaWAN frames for debugging. This is intended.
