### ISSUE TITLE
Uplink frame-counter changed small，when refresh the web

### ISSUE THREAD

**Issue by Deepdone** [brocaar/lora-app-server#26]
Refresh the page, the Uplink frame-counter just before is 1893, after a moment is 1891, then 1892 at last
![image](https://cloud.githubusercontent.com/assets/20569938/23207201/67fd92a0-f92b-11e6-94fc-c511d7c7402c.png)

**Comment by brocaar** [comment]
Could you describe how I could replicate this behaviour? At my side the Uplink frame-counter increments each time when I receive an uplink frame, which is as expected.

Do you see the same behaviour when looking at these values, but then using the `/api` endpoint? Just to make sure you're not accidentally increasing / decreasing this value by scrolling up and down (e.g. some browsers will automatically increase / decrease nummeric fields when you focus on these fields).

**Comment by Deepdone** [comment]
@brocaar  now it's work well.I guess the reason is : my net is not good! when ping the router,the delay is too high; thanks U :100:
