### ISSUE TITLE
API bug: Users list empty if no `limit` parameter

### ISSUE THREAD

**Issue by 4refr0nt** [brocaar/lora-app-server#262]
### What did you expect?
Proper response body:
```
{
  "totalCount": "1",
  "result": [
    {
      "userID": "2",
      "username": "test",
      "isAdmin": false,
      "createdAt": "2018-09-10T15:28:47.578020Z",
      "updatedAt": "2018-09-10T15:28:47.578020Z"
    }
  ]
}
```
### What happened?
Empty `result` array in response body, but `totalCount` nonzero:
```
{
  "totalCount": "1",
  "result": []
}
```
### What version are your using?
2.1.0 (from latest docker)

### How can your issue be reproduced?
Try `loraserver/api` GET `/api/organizations/{organization_id}/users` with empty `limit` parameter (proper JWT token needed,  change `{organization_id}` for proper `organization_id` with existing users)

**Comment by brocaar** [comment]
If `limit` is not set it defaults to `0` which means you only get the count but no object. Therefore you must set `limit` if you want the API to return any items in the `result`.
