### ISSUE TITLE
live lorawan frames get,live device data not

### ISSUE THREAD

**Issue by j847793745** [brocaar/lora-app-server#263]
### Is this a bug or a feature request?
feature request
### What did you expect?
how to find out what happened
### What happened?
gateway live lorawana frames display device uplink data, but device live device data not. What might be the reason, how to locate?
### What version are your using?
Docker install the latest
### How can your issue be reproduced?
n/a
### Could you share your log output?
![ebffc888ffe1a5cf8c2af4d271a7b0c](https://user-images.githubusercontent.com/30887748/45524989-b1ab3400-b803-11e8-9fd6-8feef43474cc.png)
![8ee134432155927b3c1a9a1cce9dec7](https://user-images.githubusercontent.com/30887748/45525002-b8d24200-b803-11e8-96a9-6774bf8c4c4a.png)

**Comment by brocaar** [comment]
This is not a bug or feature request. Please see https://forum.loraserver.io. This question has been asked on the forum before and you'll find hints which might help you to solve this issue.

**Comment by j847793745** [comment]
@brocaar thanks. In fact, I did find a solution, checked disable the frame counter validation, but it was only abp,  and otaa still not work, can't be activated. 
And loraserver log normal, lora-app-server log shows the following: 
level=error msg="processing rx packet error: 
get device-session error: device-session does not exist or invalid fcnt or mic" 

about otaa, how can I solve this?
