### ISSUE TITLE
Documentation does not match UI when adding devices

### ISSUE THREAD

**Issue by proffalken** [brocaar/lora-app-server#270]
### Is this a bug or a feature request?

Bug

### What did you expect?

To be able to follow the documentation at https://www.loraserver.io/lora-app-server/use/devices/ and be able to add a new node without issue

### What happened?

I got confused between the "Application Key", the "Network Key", and the documentation which talks about "AppEUI", and "AppKEY".

None of the documents or forum posts seem to indicate which of the fields in the UI map to the field names in the documentation.

*Note*: I'm happy to update the docs once I know what the mapping should be!

### What version are your using?

Latest

**Comment by brocaar** [comment]
Thanks for your feedback! I've updated the documentation. Please note that I've also released a new version of LoRa App Server which should be more clear (especially for LoRaWAN 1.0.x devices as the LoRaWAN 1.1.x fields are hidden).
