### ISSUE TITLE
CLI for lora-app-server

### ISSUE THREAD

**Issue by donsez** [brocaar/lora-app-server#273]
### Is this a bug or a feature request?
feature
### What did you expect?
contribute scripts https://github.com/CampusIoT/loraserver-cli
### What happened?
Dear Orme, I have written some bash scripts for loading in bulk gateways and devices. I can contribute to the project if you think there are useful.
### What version are your using?
2.2.0
### How can your issue be reproduced?
NA
### Could you share your log output?
NA

**Comment by brocaar** [comment]
That is great! Please share this on the forum https://forum.loraserver.io :-) This could be useful to others to use. With an eye on maintainability, I think it would be best to keep this under a separate repository. But feel free to create a pull-request to add a link to the following page:

https://github.com/brocaar/docs.loraserver.io/blob/master/content/community/links.md
