### ISSUE TITLE
jwt authentication error in live data page

### ISSUE THREAD

**Issue by mikumaycry** [brocaar/lora-app-server#278]
### Is this a bug or a feature request?
bug
### What did you expect?
To make live data tools works normally
### What happened?
error infos keeps flashing on screen when using live data tool and websocket is not connected
![jwt-error](https://user-images.githubusercontent.com/4142825/49485535-545cd700-f876-11e8-945d-211e3359855e.png)
### What version are your using?
lora-app-server v2.4.0 with chrome 70.0.3538.110
### How can your issue be reproduced?
This issue is not promised to be reproduced, just use the live data page and error keeps flashing, while other apis works normally.
### Could you share your log output?
```
time="2018-12-05T02:14:16Z" level=info msg="finished streaming call with code Unauthenticated" error="rpc error: code = Unauthenticated desc = authentication failed: jwt parse error: json: cannot unmarshal string into Go struct field Claims.exp of type int64" grpc.code=Unauthenticated grpc.method=StreamEventLogs grpc.service=api.DeviceService grpc.start_time="2018-12-05T02:14:16Z" grpc.time_ms=0.14 peer.address="127.0.0.1:45638" span.kind=server system=grpc
time="2018-12-05T02:14:16Z" level=info msg="finished streaming call with code Unauthenticated" error="rpc error: code = Unauthenticated desc = authentication failed: jwt parse error: json: cannot unmarshal string into Go struct field Claims.exp of type int64" grpc.code=Unauthenticated grpc.method=StreamEventLogs grpc.service=api.DeviceService grpc.start_time="2018-12-05T02:14:16Z" grpc.time_ms=0.139 peer.address="127.0.0.1:45638" span.kind=server system=grpc
```

**Comment by brocaar** [comment]
are you using apache, nginx or any other proxy?

**Comment by brocaar** [comment]
Can this issue be closed?
