### ISSUE TITLE
Enable prometheus metrics so that it can be easily scraped

### ISSUE THREAD

**Issue by KarthikSubramanian2** [brocaar/lora-app-server#279]
### Is this a bug or a feature request?
feature request
### What did you expect?
A prometheus metrics endpoint to consume. 
Something like localhost:8080/metrics  that will contain some valuable metrics with proper tags so that we can visualize that in a time series. I do remember we have an influx integration which is built-in and that's great. But we use prometheus a lot, and we would like to have that in lora app server as well. 
### What happened?
Metrics not available through an HTTP endpoint
### What version are your using?
2.4.0

**Comment by brocaar** [comment]
Prometheus metrics have been added in v.3.2.0.
