### ISSUE TITLE
KEYS(OTAA) field invisible in Opera browser

### ISSUE THREAD

**Issue by wireless-road** [brocaar/lora-app-server#284]
Hi!
`KEYS(OTAA)` tab empty in opera browser:
https://cloud.mail.ru/public/DQ9N/4QD4PCtCa
This tab is visible in Chrome browser for example.
Detailed description can be found here:
https://forum.loraserver.io/t/unknowndeveui-error/2857/6

**Comment by brocaar** [comment]
Using LoRa App Server 2.3.1, I can't reproduce this issue:

![image](https://user-images.githubusercontent.com/165497/50161321-c8b66200-02db-11e9-8738-d42b56d53b0f.png)

![image](https://user-images.githubusercontent.com/165497/50161330-d0760680-02db-11e9-8746-3822543bf875.png)
