### ISSUE TITLE
RX2 data rate can't be configured at RU868 server

### ISSUE THREAD

**Issue by sputnik-alarm** [brocaar/lora-app-server#285]
### Is this a bug or a feature request?
Bug.
The issue [#173](https://github.com/brocaar/lora-app-server/issues/173) is still appears in server, working on RU868 regional profile.

### What did you expect?
"rx2_dr=..." setting affects datarate of RX2 commands to the node.

### What happened?
RX2 datarate always DR_0, and not affectable by config file.

### What version are your using?
LoRa Server v2.4.1

### How can your issue be reproduced?
Configure the server to work on RU868 regional parameters with different settings "rx2_dr=...". 

### Could you share your log output?
If need.

**Comment by brocaar** [comment]
Please note that changing the `rx2_dr` requires you to restart LoRa Server **and** 1) either the device to OTAA re-activate or 2) to acknowledge the mac-command that changes the RX2 parameters on the device. LoRa Server will keep using the "old" RX2 value until the device is made aware that this parameter changed.
