### ISSUE TITLE
error in react and ui

### ISSUE THREAD

**Issue by wssq** [brocaar/lora-app-server#290]
Hi.
When i want to use npm for debugging lora-app-server, I get fallow error. Of course It is not problem in using build.
```
←→1 of 2 errors on the page
Unhandled Rejection (TypeError): Cannot read property 'code' of undefined
errorHandler
src/github.com/brocaar/lora-app-server/ui/src/stores/helpers.js:23
  20 |     },
  21 |   });
  22 | } else {
 23 |    if (error.response.obj.code === 16) {
     | ^  24 |     history.push("/login");
  25 |      } else {
  26 |       dispatcher.dispatch({
View compiled
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error
```.

**Comment by wssq** [comment]
Can anyone help me?

**Comment by brocaar** [comment]
I don't get this error. What should I do to reproduce your issue?

**Comment by gloffreda** [comment]
Got same error here.

- cloned repo
- started http-server on static folder (now i can browse localhost:8080 and get swagger
- npm start on ui folder

![image](https://user-images.githubusercontent.com/8357905/108379246-81da9480-71e4-11eb-82f0-fd83e09a5a51.png)


Getting these 2 not found on page loading and the above error on main screen

![image](https://user-images.githubusercontent.com/8357905/108379416-a9316180-71e4-11eb-9fb0-ecc0b08881a7.png)

Thanks for helping
