### ISSUE TITLE
Multi-tenancy capability between admins

### ISSUE THREAD

**Issue by DHintCo** [brocaar/lora-app-server#294]
### Is this a bug or a feature request?
A bug

### What did you expect?
That the administrator of an organization can not assign and see global administrators

### What happened?
I've created a global administrator (GA) who has assigned an organization administrator (OA) to an organization. After that I signed in with the data of the OA. Now I wanted to add more users to the organization with the OA. But not only admins were shown to me under "ASSIGN EXISTING USER", but also all GA's. This gives an organization's administrator information that is not related to their affairs. In addition, you will be logged out if you try to assign an existing user with admin rights (of any kind) to the organization.

### What version are your using?
LoRa App Server 2.4.1

Is it possible to fix it?

**Comment by brocaar** [comment]
Did you see the following config:

```toml
  # when set, existing users can't be re-assigned (to avoid exposure of all users to an organization admin)"
  disable_assign_existing_users=false
```

**Comment by DHintCo** [comment]
Uff ... I did not see it. I am really sorry. This has of course "fixed" my problem. Thank you brocaar.
