### ISSUE TITLE
Make HTTPS optional

### ISSUE THREAD

**Issue by siscia** [brocaar/lora-app-server#3]
Hi,

I actually love HTTPS, and I would need it anywhere user facing. 

However in this case, I believe it is a little too much, it makes deploy more convoluted and complex.

I would suggest to have an option to disable HTTPS, so that HTTPS still remain the default option.

**Comment by brocaar** [comment]
The issue is that in order to run both the gRPC interface and the RESTful JSON interface on the same  port, https is a technical requirement since gRPC uses http/2 and http/2 is only enabled (in Go) when using https.

**Comment by siscia** [comment]
Makes perfect sense :+1:
