### ISSUE TITLE
When multiple nodes are sending to the server it throws: drop packets and re-joining begins.

### ISSUE THREAD

**Issue by bramkennis** [brocaar/lora-app-server#31]
Feb 22 14:37:15 lora-server lora-app-server[1246]: time="2017-02-22T14:37:15+01:00" level=error msg="invalid FCnt or too many dropped frames (server_fcnt: 5, packet_fcnt: 4)" application_name=Dikberd dev_eui=0004a30b0019dcf0 node_name=PIR1-SR type=DATA_UP_FCNT
Feb 22 14:37:15 lora-server lora-app-server[1246]: time="2017-02-22T14:37:15+01:00" level=info msg="handler/mqtt: publishing error notification" topic="application/1/node/0004a30b0019dcf0/error"
Feb 22 14:37:15 lora-server lora-app-server[1246]: time="2017-02-22T14:37:15+01:00" level=error msg="invalid FCnt or too many dropped frames (server_fcnt: 4, packet_fcnt: 3)" application_name=Dikberd dev_eui=0004a30b001a0e31 node_name=PIR-Type-9 type=DATA_UP_FCNT
Feb 22 14:37:15 lora-server lora-app-server[1246]: time="2017-02-22T14:37:15+01:00" level=info msg="handler/mqtt: publishing error notification" topic="application/1/node/0004a30b001a0e31/error"
Feb 22 14:37:19 lora-server lora-app-server[1246]: time="2017-02-22T14:37:19+01:00" level=error msg="invalid FCnt or too many dropped frames (server_fcnt: 5, packet_fcnt: 4)" application_name=Dikberd dev_eui=0004a30b0019dcf0 node_name=PIR1-SR type=DATA_UP_FCNT
Feb 22 14:37:19 lora-server lora-app-server[1246]: time="2017-02-22T14:37:19+01:00" level=info msg="handler/mqtt: publishing error notification" topic="application/1/node/0004a30b0019dcf0/error"
Feb 22 14:37:19 lora-server lora-app-server[1246]: time="2017-02-22T14:37:19+01:00" level=error msg="invalid FCnt or too many dropped frames (server_fcnt: 4, packet_fcnt: 3)" application_name=Dikberd dev_eui=0004a30b001a0e31 node_name=PIR-Type-9 type=DATA_UP_FCNT
Feb 22 14:37:19 lora-server lora-app-server[1246]: time="2017-02-22T14:37:19+01:00" level=info msg="handler/mqtt: publishing error notification" topic="application/1/node/0004a30b001a0e31/error"
Feb 22 14:37:32 lora-server lora-app-server[1246]: time="2017-02-22T14:37:32+01:00" level=error msg="invalid FCnt or too many dropped frames (server_fcnt: 5, packet_fcnt: 4)" application_name=Dikberd dev_eui=0004a30b0019dcf0 node_name=PIR1-SR type=DATA_UP_FCNT
Feb 22 14:37:32 lora-server lora-app-server[1246]: time="2017-02-22T14:37:32+01:00" level=info msg="handler/mqtt: publishing error notification" topic="application/1/node/0004a30b0019dcf0/error"
Feb 22 14:37:32 lora-server lora-app-server[1246]: time="2017-02-22T14:37:32+01:00" level=error msg="invalid FCnt or too many dropped frames (server_fcnt: 4, packet_fcnt: 3)" application_name=Dikberd dev_eui=0004a30b001a0e31 node_name=PIR-Type-9 type=DATA_UP_FCNT
Feb 22 14:37:32 lora-server lora-app-server[1246]: time="2017-02-22T14:37:32+01:00" level=info msg="handler/mqtt: publishing error notification" topic="application/1/node/0004a30b001a0e31/error"
Feb 22 14:37:41 lora-server lora-app-server[1246]: time="2017-02-22T14:37:41+01:00" level=error msg="invalid FCnt or too many dropped frames (server_fcnt: 5, packet_fcnt: 4)" application_name=Dikberd dev_eui=0004a30b0019dcf0 node_name=PIR1-SR type=DATA_UP_FCNT
Feb 22 14:37:41 lora-server lora-app-server[1246]: time="2017-02-22T14:37:41+01:00" level=info msg="handler/mqtt: publishing error notification" topic="application/1/node/0004a30b0019dcf0/error"
Feb 22 14:37:42 lora-server lora-app-server[1246]: time="2017-02-22T14:37:42+01:00" level=error msg="invalid FCnt or too many dropped frames (server_fcnt: 4, packet_fcnt: 3)" application_name=Dikberd dev_eui=0004a30b001a0e31 node_name=PIR-Type-9 type=DATA_UP_FCNT
Feb 22 14:37:42 lora-server lora-app-server[1246]: time="2017-02-22T14:37:42+01:00" level=info msg="handler/mqtt: publishing error notification" topic="application/1/node/0004a30b001a0e31/error"

**Comment by brocaar** [comment]
It looks like the frame-counters were reset at the side of your node. For security reasons, LoRa Server validates the `FCnt` against the previous `FCnt` to avoid replay attacks. See also: https://github.com/brocaar/loraserver/issues/133.
