### ISSUE TITLE
Organization admin cannot add existing users

### ISSUE THREAD

**Issue by physec-rex** [brocaar/lora-app-server#315]
### Is this a bug or a feature request?
Bug

### What did you expect?
I logged in as a organization admin (but not global admin) and tried to add an existing user to the organization.
I expected to be able to add an existing user as organization admin or to not see the option to do this at all.

### What happened?
When I selected the user I wanted to add to the organization, I was logged out and sent to the login screen.

### What version are your using?
2.6.0

### How can your issue be reproduced?
Log in as organization admin and try to end

### Could you share your log output?
The browser console gave me the following error:
`GET https://<lora-app-server-domain>.de/api/users/10 401`

**Comment by brocaar** [comment]
Thanks for reporting, this has been fixed.
