### ISSUE TITLE
Super slow login Lora App Server Rpi3 + Gateway Os Full

### ISSUE THREAD

**Issue by henricazottes** [brocaar/lora-app-server#320]
### Is this a bug or a feature request?
Bug ?

### What did you expect?
Login on Lora App immediatly

### What happened?
Login on Lora app takes forever (10+ seconds after hitting enter)

### What version are your using?
Don't know where to find it.

### How can your issue be reproduced?
Self host Lora App on a raspberry pi 3 b+ with the Gateway OS Full
Login with admin/admin credentials

### Could you share your log output?
Don't know where they are located.

**Comment by brocaar** [comment]
This has to do with the (default) number of hash iterations. I will improve this for Raspberry Pi.
