### ISSUE TITLE
Lora-server unknow problem

### ISSUE THREAD

**Issue by RuhaizanFaz93** [brocaar/lora-app-server#324]
loraserver[981]: time="2019-05-29T15:33:19+08:00" level=error msg="finished unary call with code Unknown" error="rpc error: code = Unknown desc = lorawan/band: invalid data-rate" grpc.code=Unknown grpc.method=SendProprietaryPayload grpc.service=ns.NetworkServerService grpc.start_time="2019-05-29T15:33:19+08:00" grpc.time_ms=0.033 peer.address="127.0.0.1:56964" span.kind=server system=grpc

i run into this problem and i can't get reply  from the server to the end node?
this error show often but i manage to sent and receiving data to loraserver

**Comment by brocaar** [comment]
Please see: https://forum.loraserver.io/search?q=invalid%20data-rate.
