### ISSUE TITLE
can't see any data frame in device data/frame

### ISSUE THREAD

**Issue by mitsutsu** [brocaar/lora-app-server#327]
### Is this a bug or a feature request?
It is just after the environment construction, I do not know.

### What did you expect?
End-device can send and receive data after joining at OTTA.
I expected to see those data frame like the following URL
https://www.loraserver.io/lora-app-server/overview/

### What happened?
I cant' see the live data cause of "not connected to websocket API"

### What version are your using?
It's up-to-date. 

the version is below;
lora-app-server/stable,now 3.0.0 amd64
loraserver/stable,now 3.0.1 amd64

### How can your issue be reproduced?
it always happends.

### Could you share your log output?

 6月 07 13:33:55 debian64-serv lora-app-server[4655]: time="2019-06-07T13:33:55+09:00" level=info msg="js: request received" message_type=JoinReq receiver_id=4e5454572d484553 sender_id=000000 transaction_id=1962973653
 6月 07 13:33:55 debian64-serv lora-app-server[4655]: time="2019-06-07T13:33:55+09:00" level=info msg="device-keys updated" dev_eui=0080870000091311
 6月 07 13:33:55 debian64-serv lora-app-server[4655]: time="2019-06-07T13:33:55+09:00" level=info msg="js: sending response" message_type=JoinAns receiver_id=000000 result_code=Success sender_id=4e5454572d484553 transaction_id=1962973653
 6月 07 13:34:00 debian64-serv lora-app-server[4655]: time="2019-06-07T13:34:00+09:00" level=info msg="device updated" dev_eui=0080870000091311
 6月 07 13:34:01 debian64-serv lora-app-server[4655]: time="2019-06-07T13:34:01+09:00" level=info msg="device-activation created" dev_eui=0080870000091311 id=8
 6月 07 13:34:01 debian64-serv lora-app-server[4655]: time="2019-06-07T13:34:01+09:00" level=info msg="integration/mqtt: publishing message" qos=0 topic=application/1/device/0080870000091311/join
 6月 07 13:34:01 debian64-serv lora-app-server[4655]: time="2019-06-07T13:34:01+09:00" level=error msg="decode payload error" application_id=1 codec= dev_eui=0080870000091311 error="read full error: unexpected EOF" f_cnt=1 f_port=8
 6月 07 13:34:01 debian64-serv lora-app-server[4655]: time="2019-06-07T13:34:01+09:00" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=HandleUplinkData grpc.request.deadline="2019-06-07T13:34:01+09:00" grpc.service=as.ApplicationServerService grpc.start_time="2019-06-07T13:34:00+09:00" grpc.time_ms=124.511 peer.address="[::1]:51820" span.kind=server system=grpc
 6月 07 13:34:01 debian64-serv lora-app-server[4655]: time="2019-06-07T13:34:01+09:00" level=info msg="integration/mqtt: publishing message" qos=0 topic=application/1/device/0080870000091311/error
 6月 07 13:34:01 debian64-serv lora-app-server[4655]: time="2019-06-07T13:34:01+09:00" level=info msg="integration/mqtt: publishing message" qos=0 topic=application/1/device/0080870000091311/rx
 6月 07 13:34:02 debian64-serv lora-app-server[4655]: time="2019-06-07T13:34:02+09:00" level=info msg="device updated" dev_eui=0080870000091311
 6月 07 13:34:02 debian64-serv lora-app-server[4655]: time="2019-06-07T13:34:02+09:00" level=error msg="decode payload error" application_id=1 codec= dev_eui=0080870000091311 error="read full error: unexpected EOF" f_cnt=2 f_port=8
 6月 07 13:34:02 debian64-serv lora-app-server[4655]: time="2019-06-07T13:34:02+09:00" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=HandleUplinkData grpc.request.deadline="2019-06-07T13:34:03+09:00" grpc.service=as.ApplicationServerService grpc.start_time="2019-06-07T13:34:02+09:00" grpc.time_ms=33.166 peer.address="[::1]:51820" span.kind=server system=grpc
 6月 07 13:34:02 debian64-serv lora-app-server[4655]: time="2019-06-07T13:34:02+09:00" level=info msg="integration/mqtt: publishing message" qos=0 topic=application/1/device/0080870000091311/error
 6月 07 13:34:02 debian64-serv lora-app-server[4655]: time="2019-06-07T13:34:02+09:00" level=info msg="integration/mqtt: publishing message" qos=0 topic=application/1/device/0080870000091311/rx
 6月 07 13:34:03 debian64-serv lora-app-server[4655]: time="2019-06-07T13:34:03+09:00" level=info msg="device updated" dev_eui=0080870000091311
 6月 07 13:34:03 debian64-serv lora-app-server[4655]: time="2019-06-07T13:34:03+09:00" level=error msg="decode payload error" application_id=1 codec= dev_eui=0080870000091311 error="read full error: unexpected EOF" f_cnt=3 f_port=8
 6月 07 13:34:03 debian64-serv lora-app-server[4655]: time="2019-06-07T13:34:03+09:00" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=HandleUplinkData grpc.request.deadline="2019-06-07T13:34:04+09:00" grpc.service=as.ApplicationServerService grpc.start_time="2019-06-07T13:34:03+09:00" grpc.time_ms=17.799 peer.address="[::1]:51820" span.kind=server system=grpc
 6月 07 13:34:03 debian64-serv lora-app-server[4655]: time="2019-06-07T13:34:03+09:00" level=info msg="integration/mqtt: publishing message" qos=0 topic=application/1/device/0080870000091311/error
 6月 07 13:34:03 debian64-serv lora-app-server[4655]: time="2019-06-07T13:34:03+09:00" level=info msg="integration/mqtt: publishing message" qos=0 topic=application/1/device/0080870000091311/rx
 6月 07 13:34:04 debian64-serv lora-app-server[4655]: time="2019-06-07T13:34:04+09:00" level=info msg="device updated" dev_eui=0080870000091311
 6月 07 13:34:04 debian64-serv lora-app-server[4655]: time="2019-06-07T13:34:04+09:00" level=error msg="decode payload error" application_id=1 codec= dev_eui=0080870000091311 error="read full error: unexpected EOF" f_cnt=4 f_port=8
 6月 07 13:34:04 debian64-serv lora-app-server[4655]: time="2019-06-07T13:34:04+09:00" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=HandleUplinkData grpc.request.deadline="2019-06-07T13:34:05+09:00" grpc.service=as.ApplicationServerService grpc.start_time="2019-06-07T13:34:04+09:00" grpc.time_ms=107.166 peer.address="[::1]:51820" span.kind=server system=grpc
 6月 07 13:34:04 debian64-serv lora-app-server[4655]: time="2019-06-07T13:34:04+09:00" level=info msg="integration/mqtt: publishing message" qos=0 topic=application/1/device/0080870000091311/error
 6月 07 13:34:04 debian64-serv lora-app-server[4655]: time="2019-06-07T13:34:04+09:00" level=info msg="integration/mqtt: publishing message" qos=0 topic=application/1/device/0080870000091311/rx
 6月 07 13:34:05 debian64-serv lora-app-server[4655]: time="2019-06-07T13:34:05+09:00" level=info msg="device updated" dev_eui=0080870000091311
 6月 07 13:34:05 debian64-serv lora-app-server[4655]: time="2019-06-07T13:34:05+09:00" level=error msg="decode payload error" application_id=1 codec= dev_eui=0080870000091311 error="read full error: unexpected EOF" f_cnt=5 f_port=8
 6月 07 13:34:05 debian64-serv lora-app-server[4655]: time="2019-06-07T13:34:05+09:00" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=HandleUplinkData grpc.request.deadline="2019-06-07T13:34:06+09:00" grpc.service=as.ApplicationServerService grpc.start_time="2019-06-07T13:34:05+09:00" grpc.time_ms=111.745 peer.address="[::1]:51820" span.kind=server system=grpc
 6月 07 13:34:05 debian64-serv lora-app-server[4655]: time="2019-06-07T13:34:05+09:00" level=info msg="integration/mqtt: publishing message" qos=0 topic=application/1/device/0080870000091311/error
 6月 07 13:34:05 debian64-serv lora-app-server[4655]: time="2019-06-07T13:34:05+09:00" level=info msg="integration/mqtt: publishing message" qos=0 topic=application/1/device/0080870000091311/rx
 6月 07 13:34:06 debian64-serv lora-app-server[4655]: time="2019-06-07T13:34:06+09:00" level=info msg="device updated" dev_eui=0080870000091311
 6月 07 13:34:07 debian64-serv lora-app-server[4655]: time="2019-06-07T13:34:07+09:00" level=error msg="decode payload error" application_id=1 codec= dev_eui=0080870000091311 error="read full error: unexpected EOF" f_cnt=6 f_port=8
 6月 07 13:34:07 debian64-serv lora-app-server[4655]: time="2019-06-07T13:34:07+09:00" level=info msg="integration/mqtt: publishing message" qos=0 topic=application/1/device/0080870000091311/error
 6月 07 13:34:07 debian64-serv lora-app-server[4655]: time="2019-06-07T13:34:07+09:00" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=HandleUplinkData grpc.request.deadline="2019-06-07T13:34:07+09:00" grpc.service=as.ApplicationServerService grpc.start_time="2019-06-07T13:34:06+09:00" grpc.time_ms=115.553 peer.address="[::1]:51820" span.kind=server system=grpc
 6月 07 13:34:07 debian64-serv lora-app-server[4655]: time="2019-06-07T13:34:07+09:00" level=info msg="integration/mqtt: publishing message" qos=0 topic=application/1/device/0080870000091311/rx
 6月 07 13:34:08 debian64-serv lora-app-server[4655]: time="2019-06-07T13:34:08+09:00" level=info msg="device updated" dev_eui=0080870000091311
 6月 07 13:34:08 debian64-serv lora-app-server[4655]: time="2019-06-07T13:34:08+09:00" level=error msg="decode payload error" application_id=1 codec= dev_eui=0080870000091311 error="read full error: unexpected EOF" f_cnt=7 f_port=8
 6月 07 13:34:08 debian64-serv lora-app-server[4655]: time="2019-06-07T13:34:08+09:00" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=HandleUplinkData grpc.request.deadline="2019-06-07T13:34:09+09:00" grpc.service=as.ApplicationServerService grpc.start_time="2019-06-07T13:34:08+09:00" grpc.time_ms=14.67 peer.address="[::1]:51820" span.kind=server system=grpc
 6月 07 13:34:08 debian64-serv lora-app-server[4655]: time="2019-06-07T13:34:08+09:00" level=info msg="integration/mqtt: publishing message" qos=0 topic=application/1/device/0080870000091311/error
 6月 07 13:34:08 debian64-serv lora-app-server[4655]: time="2019-06-07T13:34:08+09:00" level=info msg="integration/mqtt: publishing message" qos=0 topic=application/1/device/0080870000091311/rx
 6月 07 13:34:09 debian64-serv lora-app-server[4655]: time="2019-06-07T13:34:09+09:00" level=info msg="device updated" dev_eui=0080870000091311
 6月 07 13:34:09 debian64-serv lora-app-server[4655]: time="2019-06-07T13:34:09+09:00" level=error msg="decode payload error" application_id=1 codec= dev_eui=0080870000091311 error="read full error: unexpected EOF" f_cnt=8 f_port=8
 6月 07 13:34:09 debian64-serv lora-app-server[4655]: time="2019-06-07T13:34:09+09:00" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=HandleUplinkData grpc.request.deadline="2019-06-07T13:34:10+09:00" grpc.service=as.ApplicationServerService grpc.start_time="2019-06-07T13:34:09+09:00" grpc.time_ms=12.578 peer.address="[::1]:51820" span.kind=server system=grpc
 6月 07 13:34:09 debian64-serv lora-app-server[4655]: time="2019-06-07T13:34:09+09:00" level=info msg="integration/mqtt: publishing message" qos=0 topic=application/1/device/0080870000091311/error
 6月 07 13:34:09 debian64-serv lora-app-server[4655]: time="2019-06-07T13:34:09+09:00" level=info msg="integration/mqtt: publishing message" qos=0 topic=application/1/device/0080870000091311/rx
 6月 07 13:34:10 debian64-serv lora-app-server[4655]: time="2019-06-07T13:34:10+09:00" level=info msg="device updated" dev_eui=0080870000091311
 6月 07 13:34:10 debian64-serv lora-app-server[4655]: time="2019-06-07T13:34:10+09:00" level=error msg="decode payload error" application_id=1 codec= dev_eui=0080870000091311 error="read full error: unexpected EOF" f_cnt=9 f_port=8
 6月 07 13:34:10 debian64-serv lora-app-server[4655]: time="2019-06-07T13:34:10+09:00" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=HandleUplinkData grpc.request.deadline="2019-06-07T13:34:11+09:00" grpc.service=as.ApplicationServerService grpc.start_time="2019-06-07T13:34:10+09:00" grpc.time_ms=106.128 peer.address="[::1]:51820" span.kind=server system=grpc
 6月 07 13:34:10 debian64-serv lora-app-server[4655]: time="2019-06-07T13:34:10+09:00" level=info msg="integration/mqtt: publishing message" qos=0 topic=application/1/device/0080870000091311/error
 6月 07 13:34:10 debian64-serv lora-app-server[4655]: time="2019-06-07T13:34:10+09:00" level=info msg="integration/mqtt: publishing message" qos=0 topic=application/1/device/0080870000091311/rx
 6月 07 13:34:11 debian64-serv lora-app-server[4655]: time="2019-06-07T13:34:11+09:00" level=info msg="device updated" dev_eui=0080870000091311
 6月 07 13:34:11 debian64-serv lora-app-server[4655]: time="2019-06-07T13:34:11+09:00" level=error msg="decode payload error" application_id=1 codec= dev_eui=0080870000091311 error="read full error: unexpected EOF" f_cnt=10 f_port=8
 6月 07 13:34:11 debian64-serv lora-app-server[4655]: time="2019-06-07T13:34:11+09:00" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=HandleUplinkData grpc.request.deadline="2019-06-07T13:34:12+09:00" grpc.service=as.ApplicationServerService grpc.start_time="2019-06-07T13:34:11+09:00" grpc.time_ms=14.203 peer.address="[::1]:51820" span.kind=server system=grpc
 6月 07 13:34:11 debian64-serv lora-app-server[4655]: time="2019-06-07T13:34:11+09:00" level=info msg="integration/mqtt: publishing message" qos=0 topic=application/1/device/0080870000091311/error
 6月 07 13:34:11 debian64-serv lora-app-server[4655]: time="2019-06-07T13:34:11+09:00" level=info msg="integration/mqtt: publishing message" qos=0 topic=application/1/device/0080870000091311/rx

**Comment by brocaar** [comment]
Please see https://forum.loraserver.io/search?q=not%20connected%20to%20websocket%20API.
