### ISSUE TITLE
API users columns email and note

### ISSUE THREAD

**Issue by geniv** [brocaar/lora-app-server#328]
### Is this a bug or a feature request?
bug: yes

### What did you expect?
I expect list user with email and note values

### What happened?
problem is with endpoint: GET /api/users
if I want get email and note:
"email": "string",
"note": "string",
on this endpoint are these columns empty but if I use endpoint to get specify user then this values are correctly filled.

### What version are your using?
api version: 1.0.0

### How can your issue be reproduced?
save any value to email or note and check endpoin list with all users

**Comment by brocaar** [comment]
Actually these fields should not be present when listing users. They were added to the `UserListItem` type (in the Protobuf definition), but it is correct these are not filled. The reason is that this could leak information to organization admins.
