### ISSUE TITLE
Updating the device via api deletes optional values

### ISSUE THREAD

**Issue by TestingMandy** [brocaar/lora-app-server#330]
### Is this a bug or a feature request?
Bug

### What did you expect?
I want to update the deviceProfileId for a device. 
All json values in the body for the/api/devices/{device.dev_eui} PUT request are define optional. For the request I have to set the application ID and devEUI too. So the body looks like:
{
  "device": {
   "applicationID": "string",
   "devEUI": "string",
   "deviceProfileID": "string"
}
I expected, that the old, already given values are not overwritten. 

### What happened?
The optional values name and description are updated with empty strings and the skipFCntCheck  is updated to false.
An empty name also has the impact, that the device in the application overview on the server website is not linked.
![application](https://user-images.githubusercontent.com/51744763/59346297-4353bd80-8d12-11e9-80d4-c3591e8b987d.jpg)

**Comment by brocaar** [comment]
This is intended behavior. When a key is not given, it will overwrite the current value with an empty value (empty string, false in case of a bool, 0 in case of an int, ....). I believe this is also in line with the HTTP PUT verb.
