### ISSUE TITLE
What the setting for AS923

### ISSUE THREAD

**Issue by RuhaizanFaz93** [brocaar/lora-app-server#331]
![Lora Band](https://user-images.githubusercontent.com/51153056/59488014-ecd0b580-8eb0-11e9-8d7c-356fcd0424a3.PNG)

What should i set fro the rest of extra channel if i'm using AS923 band?

**Comment by brocaar** [comment]
Please post your question on the forum: forum.loraserver.io, it is a better place for support related questions.
