### ISSUE TITLE
Changing of device class after initial setup is ignored

### ISSUE THREAD

**Issue by demetz** [brocaar/lora-app-server#333]
### Is this a bug or a feature request?
Bug

### What did you expect?
I created a device with class-a and class-c, which only supports class-a. After discovering my error, I disabled class-c. Hence, downlink messages should be queued and only be delivered later.

### What happened?
The downlink message was signed with delivery "Immediately", therefore Loraserver tried to deliver the message without waiting for the next uplink.

### What version are your using?
3.0.?

### How can your issue be reproduced?
1. create a device with class-a and class-c
2. after setting it up, disable class-c
3. send a downlink to the device. It will be delivered immediately, instead of waiting for the next slot.

### Could you share your log output?
loraserver_1  | 2019-06-28T11:40:06.872807892Z time="2019-06-28T11:40:06Z" level=warning msg="device-queue item discarded due to timeout" dev_eui=[...] device_queue_item_fcnt=12

**Comment by brocaar** [comment]
After changing the device-profile, you might need to re-activate the device (OTAA or ABP). This is needed as the Device Profile contains the boot parameters of the device, but these might change over time (and are stored in the device-profile). E.g. LoRa Server might decide to re-configure the device to use different parameters. Also, the device could have indicated that it changed from Class-A to Class-C using mac-commands.

I've added this note: https://github.com/brocaar/lora-app-server/commit/ff43d6784b13020d7b5a57d7db6183a159e1a323.
