### ISSUE TITLE
Could not find queue in real node send data 

### ISSUE THREAD

**Issue by T7T** [brocaar/lora-app-server#34]
![103151763663688390](https://cloud.githubusercontent.com/assets/22682729/23821101/d2f77d6a-0663-11e7-8bbf-16bd6e61f9a3.png)

![135199015306591848](https://cloud.githubusercontent.com/assets/22682729/23821027/1fa4a0ae-0662-11e7-8d35-c33cc975b43a.png)

![Uploading wxid_e7klek6s53lg21_1489212539986_57.png…]()

lora-app-server vision is 0.4.0

**Comment by brocaar** [comment]
Note that this is an `info` log, nothing to worry about (maybe I should change it to `debug`). It means there is a receive window, but there is nothing in the downlink queue to send to the node.

**Comment by T7T** [comment]
debug log  is needed by who wants to find out why  the node sending payload does not decode.
