### ISSUE TITLE
API missing endpoint GET multicast-groups/{multicast_group_id}/devices

### ISSUE THREAD

**Issue by geniv** [brocaar/lora-app-server#344]
### Is this a bug or a feature request?
bug: yes
the bigges bug: YES

### What did you expect?
GET /api/multicast-groups/{multicast_group_id}/devices
endpoint for ADD (post) and for REMOVE (delete) without LIST (GET) is useless.
I expect endpoint: /api/multicast-groups/{multicast_group_id}/devices 
If I call this endpoint I get: Method Not Allowed - this is tottaly wrong

### What happened?
I want list devices in multicast group. How?

### What version are your using?
api version: 1.0.0

**Comment by geniv** [comment]
I wonder why this endpoint is missing when in the application (port 8080) this functionality is and in the API is not ???

**Comment by brocaar** [comment]
Everything that is possible in the web-interface is possible with the API as the web-interface is built on top of the API :wink: 

What you need to use is this endpoint:

![image](https://user-images.githubusercontent.com/165497/62029333-990cf800-b1e2-11e9-8407-836bfbd349c1.png)

And filter on `multicastGroupID`.

**Comment by geniv** [comment]
@brocaar ok, thanks, I expect endpoint: `/api/multicast-groups/{multicast_group_id}/devices` never mind, I already understand how it is intended
