### ISSUE TITLE
Show missing service-profile popup when adding gateway to org. without SP

### ISSUE THREAD

**Issue by golovlevviktor** [brocaar/lora-app-server#345]
### Is this a bug or a feature request?
bug
### What did you expect?
I want to add gateway to the clear server
### What happened?
After I have added Network-server I wanted to add gateway, but field for network-server was empty and there was no any alert message.

Ability to add network-server appears only after I added service profile.

So It will be cool if there will be alert message like when I want to crete device-profile without service-profile =)

### What version are your using?
3

**Comment by mister4yk** [comment]
First of all you must add service profile.

**Comment by golovlevviktor** [comment]
> First of all you must add service profile.

As you can read above I've found it out already, thanks

**Comment by brocaar** [comment]
Thanks, I would consider this more as an improvement than bug (it is an inconvenience, but nothing is broken). Anyway it is a good thing to improve :+1:
