### ISSUE TITLE
npm start 

### ISSUE THREAD

**Issue by ChrisAuYeung** [brocaar/lora-app-server#346]
I use the **npm start**  in the ./ui dir,get the error:
Failed to compile
./src/index.css (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-3-1!./node_modules/postcss-loader/src??postcss!./src/index.css)
Error: Cannot find module '@csstools/normalize.css'

**Comment by brocaar** [comment]
Please fill in the template when creating an issue. Without providing any context, all I can say is `npm start` does work for me :wink: 

https://www.loraserver.io/lora-app-server/community/source/ contains some info when building from source.
