### ISSUE TITLE
CPU workload caused by PostgreSQL

### ISSUE THREAD

**Issue by DHintCo** [brocaar/lora-app-server#348]
### Is this a bug or a feature request?
Bug

### What happened?
After starting a test with more than 150 nodes, the CPU workload was almost 200% (red arrow, two cores).
![2019-08-20 11_22_39-Portainer](https://user-images.githubusercontent.com/47554220/63347771-21049e80-c358-11e9-99eb-96ab5066925c.png)

### What version are your using?
LoRa-App-Server: v2.6.1
PostgreSQL v9.6-alpine

### How can your issue be reproduced?
By unchecking a service user as global admin (in the app-server)

The service user is used to allow the application to transmit downlink to each node. In our test setup of 150 nodes, we saw that the CPU workload increases to almost 200% (red arrow). After unchecking the service user as global admin (green arrow), the CPU workload was decreased. This CPU workload was caused by PostgreSQL which uses the following query. 
![2019-08-20 11_25_14-Portainer](https://user-images.githubusercontent.com/47554220/63348069-d6375680-c358-11e9-88b5-c806fedbcdc3.png)
This query takes a lot of processing time. 
Is it possible to simplify the query whether the user is allowed to transmit downlink?

Best regards
DHintCo

**Comment by brocaar** [comment]
I believe this issue has already been addressed by #300 (and pull-request #302).

**Comment by brocaar** [comment]
I'm closing this issue as I think hit has been addressed by the above changes. I've also started making the query more specific for each validator, as it is not always needed to join in all tables. This should also increase the performance.
