### ISSUE TITLE
Organisation selection drop-down limited to 10 entries

### ISSUE THREAD

**Issue by sa-wilson** [brocaar/lora-app-server#350]
### Is this a bug or a feature request?
Bug
### What did you expect?
All organisations to be visible in the drop down in the Sidebar nav (User is a global Admin).
### What happened?
Only the first 10 organisations are visible.
### What version are your using?
3.2.0
### How can your issue be reproduced?
Login as a user with access to more than 10 organisations.

**Comment by brocaar** [comment]
This is by design. It will show you 10 orgs by default, but as soon as you start typing, it will update the list of max 10 items to orgs. matching your input.
