### ISSUE TITLE
Feature Request: Remember Rows per page selection

### ISSUE THREAD

**Issue by sa-wilson** [brocaar/lora-app-server#351]
### Is this a bug or a feature request?
Feature Request
### What did you expect?
When the Rows per page is changed from the default of 10 that the setting is retained on the same browser session. Would this be possible using a cookie or the local storage apis?

**Comment by brocaar** [comment]
Yes, this would be a good one and should be fairly simple as all tables are using the same React component. https://github.com/brocaar/lora-app-server/blob/master/ui/src/components/DataTable.js#L17

This could work the same as the organization id storage: https://github.com/brocaar/lora-app-server/blob/master/ui/src/stores/SessionStore.js#L46.
