### ISSUE TITLE
UI Error message `object does not exist` when last seen is empty

### ISSUE THREAD

**Issue by KarthikSubramanian2** [brocaar/lora-app-server#359]
Though it doesn't impact any functionality, there is an error message that pops up when the last seen is empty on devices. 

```
object does not exist(code:5)
```

lora-app-server version : 3.2.1

**Comment by KarthikSubramanian2** [comment]
Analyzing the code, this is what it seems to be. 

While displaying the `downlink queue` in the `device details` page, the device activation is being fetched from the database and the error appears when the device has not been activated. 

https://github.com/brocaar/lora-app-server/blob/9614b996010b284fe08bdab019a0bc16d62a767e/internal/api/external/device_queue.go#L167

**Comment by brocaar** [comment]
Thanks, I have fixed this in the above commit.
