### ISSUE TITLE
lora-server-app not starting

### ISSUE THREAD

**Issue by avishnev** [brocaar/lora-app-server#363]
i configured lora-server-app on ubuntu 18.04 with 2 databases as it said on the list.loraserver is configured with dsn="postgres://loraserver_ns:dbpassword@localhost/loraserver_ns?sslmode=disable" and lora-server-app is configured with dsn="postgres://loraserver_as:dbpassword@localhost/loraserver_as?sslmode=disable" just as documentation states. I cant start lora-app-server.I get the following error
Sep 25 14:58:32 ip-172-26-15-28 systemd[1]: Stopped LoRa App Server.
Sep 25 14:58:32 ip-172-26-15-28 systemd[1]: Started LoRa App Server.
Sep 25 14:58:32 ip-172-26-15-28 lora-app-server[28230]: time="2019-09-25T14:58:32Z" le
vel=info msg="starting LoRa App Server" docs="https://www.loraserver.io/" version=3.3.
1
Sep 25 14:58:32 ip-172-26-15-28 lora-app-server[28230]: time="2019-09-25T14:58:32Z" le
vel=info msg="storage: setting up storage package"
Sep 25 14:58:32 ip-172-26-15-28 lora-app-server[28230]: time="2019-09-25T14:58:32Z" le
vel=info msg="storage: setting up Redis pool"
Sep 25 14:58:32 ip-172-26-15-28 lora-app-server[28230]: time="2019-09-25T14:58:32Z" le
vel=info msg="storage: connecting to PostgreSQL database"
Sep 25 14:58:32 ip-172-26-15-28 lora-app-server[28230]: time="2019-09-25T14:58:32Z" le
vel=info msg="storage: applying PostgreSQL data migrations"
Sep 25 14:58:32 ip-172-26-15-28 lora-app-server[28230]: time="2019-09-25T14:58:32Z" le
vel=fatal msg="setup storage error: storage: applying PostgreSQL data migrations error
: Unable to create migration plan because of 0002_node_frame_log.sql: unknown migratio
n in database"

I googled and it states that i have to use 2 different database names.i assume it is for dsn. please help!!!!!

**Comment by brocaar** [comment]
Please use GitHub issues for bugs of feature requests. The forum is a better place for community support (I believe I already answered your question on the forum).
