### ISSUE TITLE
JWT token for the REST API interactive console

### ISSUE THREAD

**Issue by ymkins** [brocaar/lora-app-server#39]
The REST API interactive console wont work since 0.6.0 update.

Response Body
```
{
  "error": "authentication failed: get token from context error: no authorization-data in metadata",
  "code": 16
}
```
Seems like have to set the Grpc-Metadata-Authorization header field according to the documentation.

**Comment by brocaar** [comment]
Note that you can past a JWT token in the console (right top). To generate one, you could use the `/api/internal/login` endpoint (from the api console).

**Comment by ymkins** [comment]
Thanks!

**Comment by AnnaLupanova** [comment]
I am having the same problem. I inserted the token into the upper corner. But doesn't work

**Comment by NelsonKon** [comment]
I am having the same problem. I inserted the token into the upper corner. But doesn't work.  What could be the problem?
