### ISSUE TITLE
make build with undefined migrations.AssetDir erro

### ISSUE THREAD

**Issue by tc1989tc** [brocaar/lora-app-server#43]
detail error message:
# command-line-arguments
cmd/lora-app-server/main.go:70: undefined: migrations.AssetDir
cmd/lora-app-server/main.go:262: undefined: static.AssetDir
cmd/lora-app-server/main.go:263: undefined: static.AssetInfo
Makefile:8: recipe for target 'build' failed
make: *** [build] Error 2

how to fix this? thanks

**Comment by brocaar** [comment]
This is the same issue as #38.
