### ISSUE TITLE
Node list not returned

### ISSUE THREAD

**Issue by kuripiiritus** [brocaar/lora-app-server#5]
Hei

There seems to be some issue with retuning the node list. 
current config: loraserver on 0.12.3 lora-app-server on 0.1.3

When requesting the node list (GET /api/node) the result should be as per description 
`{
  "result": [
    {
      "appEUI": "string",
      "appKey": "string",
      "channelListID": "string",
      "devEUI": "string",
      "name": "string",
      "relaxFCnt": true,
      "rx1DROffset": 0,
      "rx2DR": 0,
      "rxDelay": 0,
      "rxWindow": "RX1"
    }
  ],
  "totalCount": "string"
}`

unfortunately it only replies with 
`{
  "totalCount": "7"
}`
It gets the count, but does not display the actual nodes.

adding the offset and limit  (GET /api/node/0/100) returns not found. Doing the same in the 0.1.1 version server, works flawlessly.

Br,
Kuldar Loime

**Comment by sopach** [comment]
Hi,

I Have exactly the same problem, with the same configuration.

Br.

Stanislav

**Comment by brocaar** [comment]
Sorry for my late reply, I was on vacation. Please see the api documentation: 

![image](https://cloud.githubusercontent.com/assets/165497/20244917/de505fe2-a993-11e6-9c66-dac44e8ceb41.png)

You should use `?limit=10&offset=0` now :-) This makes the api a bit cleaner.

**Comment by kuripiiritus** [comment]
Thanks for the reply. This does look better :)

**Comment by hecko** [comment]
IMO the docs to this are still rather unclear - I had to search here to find the answer, which sort of demonstrates this solution (or rather information) should really be specifically mentioned in the API call description.

**Comment by brocaar** [comment]
This will be properly fixed in the next version as url query arguments are now correctly documented in the Swagger specs (by https://github.com/grpc-ecosystem/grpc-gateway). 

![screen shot 2017-01-29 at 17 38 08](https://cloud.githubusercontent.com/assets/165497/22405911/bdb0f592-e649-11e6-8682-744351317da0.png)
