### ISSUE TITLE
About SSL generated by openssl

### ISSUE THREAD

**Issue by onlymuxia** [brocaar/lora-app-server#57]
I think it's very necessary to notice that SSL Certificates generated by openssl is in a illegal-format.

And for developers it is easy to get a legal SSL Certificates with tool in crypto/tls/generate_cert.go

**Comment by ymkins** [comment]
@onlymuxia
What did you mean "illegal-format"?
I know about trouble with providing the subjectAltName on openssl command line. It can be solved with sub-shell command.
Can you please point for openssl defects?

**Comment by onlymuxia** [comment]
Using SSL Certificates generated by openssl , I get this error:
       crypto/tls: failed to parse key PEM data

**Comment by onlymuxia** [comment]
@ymkins 
Using SSL Certificates generated by openssl , I get this error:
crypto/tls: failed to parse key PEM data

**Comment by brocaar** [comment]
@onlymuxia are you sure it is an openssl issue? The post-install script of the `.deb` package uses openssl to generate a self-signed certificate on installation. So far that works great for me and I've used this to install LoRa App Server for many people.

https://github.com/brocaar/lora-app-server/blob/master/packaging/deb/post-install.sh#L65

**Comment by onlymuxia** [comment]
@brocaar 
              Im sorry that I try again on another computer and SSL generated by openssl is OK.
              Actually it is my fault And I Will  check my config file again.
