### ISSUE TITLE
Add Application session key and Network session key generator

### ISSUE THREAD

**Issue by minggi** [brocaar/lora-app-server#60]
Please add a Application session key and Network session key generator in the app. Same like the device address generator.

**Comment by brocaar** [comment]
That would indeed be nice, feel free to help btw 😉 It would only need some front-end / JS work (for the DevAddr this is different, because of the NetID configuration).

**Comment by ciudadoscura** [comment]
I'm working on it.

**Comment by brocaar** [comment]
This was already implemented / merged.
