### ISSUE TITLE
501 error when post or get using the api

### ISSUE THREAD

**Issue by wangzheng2013** [brocaar/lora-app-server#62]
when I try to use the api to create a new gateway, server returns the 501 error. Nevertheless, I can use the api to create new users.

Response Body
{
  "error": "unknown method CreateGateway",
  "code": 12
}
Response Code
501

This error confused me, and how can I solve it?

**Comment by brocaar** [comment]
You need to upgrade your LoRa Server instance. See also the release notes https://github.com/brocaar/lora-app-server/releases/tag/0.7.0.
