### ISSUE TITLE
Failed to start LoRa App Server.

### ISSUE THREAD

**Issue by VahrushevSA** [brocaar/lora-app-server#63]
After version 0.5.0 I can not run Lora app server. I ask to help, what can be done.

**Comment by brocaar** [comment]
Check the logs? Check the release notes about what has changed and what settings needs to be updated?

**Comment by VahrushevSA** [comment]
It does not start because of postgresql.
line: POSTGRES_DSN=postgres://loraserver:password@localhost/loraserver?sslmode=disable
If you change to drain: POSTGRES_DSN=postgres://loraserver:password@localhost/loraserver?sslmode=disabl
Then lora app server starts with errors.

**Comment by VahrushevSA** [comment]
I have postgresql v 9.6.2

**Comment by brocaar** [comment]
> Then lora app server starts with errors.

Which errors? ;-)

**Comment by VahrushevSA** [comment]
Thanks Brocaar, figured out.
Put the jwt-secret and lora app server started.
