### ISSUE TITLE
Decrypt received data from the node

### ISSUE THREAD

**Issue by ehsanmqn** [brocaar/lora-app-server#65]
Dear Brocaar, 
Thank you for your great work,
I started the server as instructions from documents and  configured a gateway to send data to the broker. I have created a lora node that publish temperature to the server. When I subscribe to it's MQTT topic, I get encrypted data such as "MjIuMDAACQnpCfwEBQ==". Can you guide me how I can decrypt this data?

**Comment by claudyus** [comment]
It is base64 encoder, just use a script or an online tool to  decode it. Your message is decoded as "22.00". Hope this could help you!

**Comment by ehsanmqn** [comment]
Thank you very much, It was very useful

**Comment by pmiam999** [comment]
ehsanmqn: on a unix plateform : base64 -d <<< $payload | hexdump -C
