### ISSUE TITLE
how to show the rx data?

### ISSUE THREAD

**Issue by lancezhangsf** [brocaar/lora-app-server#7]
Hi, Brocaar,

i can use the app server api ,and show the rx data number ,but i can't find the rx data ,can you give some advice  ??

**Comment by hecko** [comment]
you probably want to use mqtt client and subscribe to # topic to see all the rx/tx packets and what is happening on the server

**Comment by lancezhangsf** [comment]
hi ,hecko 

thank you for your answer.  I have settled。
