### ISSUE TITLE
Send Downlink Data with MQTT not working

### ISSUE THREAD

**Issue by Movsun** [brocaar/lora-app-server#73]
Hello brocaar, 

I try to send downlink message via MQTT. I follow the instruction and publish the json data to "application/[applicationID]/node/[devEUI]/tx" but I didn't see my message in "/api/nodes/{devEUI}/queue". 
If I use HTTP Post to send, It works. 
Thank you in advance,

Movsun

**Comment by brocaar** [comment]
Are you sure you replaced the `[applicationID]` and `[devEUI]` with the correct application id and (lowercase) devEUI? Could you also check the lora-server-logs?

**Comment by brocaar** [comment]
Just checked, but I don't see any problems with the latest version. When enqueueing data over MQTT, I get the following logs (lora-app-server):

```
INFO[8237] handler/mqtt: data-down payload received      topic="application/1/node/0101010101010101/tx"
INFO[8237] downlink queue item enqueued                  dev_eui=0101010101010101 id=1
```
