### ISSUE TITLE
authentication failed: not authorized but can access to :8080/api

### ISSUE THREAD

**Issue by vravoire** [brocaar/lora-app-server#77]
I can access to https://localhost:8080/api but when i "try it out!" for exemple GET /api/application
I have "error": "authentication failed: not authorized",
          "code": 16

Everything in https://localhost:8080/ is ok
I look into this issues #41, but it didn't fix 

maybe it's because  grpc.WithPerRPCCredentials method is in the wrong place (i write in google.golang.org/grpc/clientconn.go)

**Comment by brocaar** [comment]
You need to generate a JWT token and fill this in the JWT token field (right top corner). See also https://docs.loraserver.io/lora-app-server/api/#authentication-and-authorization.

**Comment by vravoire** [comment]
Yes I already do this :
I generate a token, I put the secret in /etc/default/lora-app-server (JWT_SECRET) and i fill the jwt token in the token field.

**Comment by brocaar** [comment]
Could you try the `/api/internal/login` endpoint to generate a JWT token? For that token no authentication is needed. After posting your credentials it should give you a JWT token. Then you're able to compare it with the token that you generated yourself.

**Comment by vravoire** [comment]
ok it works ! 
Thanks for your answer, you do a great job

**Comment by geppoleppo** [comment]
HI,
i have followed the instruction but doesn't work.
The browser respond: "fetching resource list: undefined; Please wait."

**Comment by RogerioCassares** [comment]
Hello @geppoleppo with me happened the same thing. 

But like @brocaar had said, try to generate the JWT token in /api/internal/login with your password and login:

![captura de tela de 2017-05-19 17-28-28](https://cloud.githubusercontent.com/assets/25107890/26265724/a14c0610-3cb8-11e7-8aa4-e2476bfc60e7.png)

then update to your folder in your machine at /etc/default/lora-app-server

![captura de tela de 2017-05-19 17-30-43](https://cloud.githubusercontent.com/assets/25107890/26265807/eb156dae-3cb8-11e7-883a-2c72d1e025e0.png)

Just copy in "JWT token field (right top corner)". DO NOT PRESS ENTER!!!

And just let the token there, and run the commands on api!
