### ISSUE TITLE
MIGRATE_NODE_SESSIONS= missing

### ISSUE THREAD

**Issue by glederer007** [brocaar/lora-app-server#79]
Hello Orne,

Apparently "MIGRATE_NODE_SESSIONS=" is missing from /etc/default/lora-app-server when it is created through "sudo apt-get install lora-app-server". And if it is missing, lora-app-server won't start at all. Could you check it?

Regards,

Gabor

PS.: As a clarification. This happened when a brand new, clean install was made (without any databases or anything to migrate!)

**Comment by brocaar** [comment]
This was a really old migration flag and the code has been cleaned up recently, because of that the config flag was removed also. I'll try a clean install myself, but I don't see (yet) why LoRa App Server would not start because of that?

Do you have any error message?

**Comment by brocaar** [comment]
Just installing LoRa App Server on a clean (VM) instance, but I can't reproduce this issue...

**Comment by glederer007** [comment]
I installed loraserver / lora-app-server on a cloud service (arubacloud) a couple of days ago when I couldn't start lora-app-server. Unfortunately I didn't save the error logs. On Friday I will install another vps as well, I will try to reproduce the error then.

**Comment by brocaar** [comment]
Perfect, let's keep this issue open until then.

**Comment by glederer007** [comment]
Sorry, I was not able to reproduce the issue. I will close the issue.
