### ISSUE TITLE
I want to call the restful method DownlinkQueue fail

### ISSUE THREAD

**Issue by leecxn2012** [brocaar/lora-app-server#81]
when I call the GET /api/nodes/{devEUI}/queue method ,

			resource = client.resource("https://192.168.0.22:8080/api/nodes/0202020202020202/queue");
			resource.header("Grpc-Metadata-Authorization",map.get("jwt").toString() );
			
			response = resource.type("application/json;charset=UTF-8").get(ClientResponse.class);

I get the error
{"error":"authentication failed: jwt parse error: token contains an invalid number of segments","code":16}

how to do ?

**Comment by leecxn2012** [comment]
I got it ,
should that
response = resource.header("Grpc-Metadata-Authorization",map.get("jwt")).type("application/json;charset=UTF-8").get(ClientResponse.class);

**Comment by achrafitou** [comment]
Hi leecxn2012
I'm trying to do the same thing but having issues with ssl. Did your program work right away?
