### ISSUE TITLE
ABP settings not available for users that are not global admins

### ISSUE THREAD

**Issue by iBrick** [brocaar/lora-app-server#85]
Hi, I have found a bug with permissions.
If a user is a global admin he can set ABP settings, but if the user is Organisation admin - ABP settings is not available for him (grey).

**Comment by brocaar** [comment]
Thanks for reporting this. I've confirmed this issue and will fix it asap :-)

**Comment by iBrick** [comment]
Hmmm, I've checked this but still issue is there.

**Comment by iBrick** [comment]
Sorry, my wrong, it works.
