### ISSUE TITLE
Can't run lora-app-server with docker.

### ISSUE THREAD

**Issue by romeogoon** [brocaar/lora-app-server#86]
Hello Brocaar,

I send data from end-device with LoRaWAN ClassA EU 863-870MHz ISM band to LoRa Gateway then forward packet to lora-gateway-bridge already.

I run loraserver with docker already.

but I can't run lora-app-server I had a error message follow in photo.

![1](https://cloud.githubusercontent.com/assets/19875055/26057019/e333e918-39a1-11e7-9670-df370a629472.png)

Best Regards,
Olarn

**Comment by brocaar** [comment]
Hi Olarn, the containers provided are (currently) only meant for development and running the testsuite. Providing Docker containers for setting up a LoRaWAN environment is on my list, but that needs some more work.
