### ISSUE TITLE
node session update

### ISSUE THREAD

**Issue by utopiaprince** [brocaar/lora-app-server#87]
lora-app-server: 0.9.1
---
in the node interface，i change the ADR value and submit it.
then lora-app-server update the node-seesion into postgres, but it don't save node-session to loraserver.
![image](https://cloud.githubusercontent.com/assets/3860757/26189438/467b19e2-3bd7-11e7-9bc2-97b28bb4ca75.png)
but if i delete or activate node. the lora-app-server can push node-session to loraserver, and loraserver change it in redis server.
so my question is that is this specially designed for any purpose i don't konw?

**Comment by brocaar** [comment]
That is intentional, please see the note on top 😉 

> Please note that changes made below (when updating a node) only have effect after (re)activating the node (either ABP or OTAA).
