### ISSUE TITLE
can't add new application

### ISSUE THREAD

**Issue by mikumaycry** [brocaar/lora-app-server#88]
Error pq: insert or update on table "application" violates foreign key constraint "application_organization_id_fkey" (code: 2)

Run Lora-App-Server from master branch, Error occurred when adding first application

**Comment by brocaar** [comment]
It is very likely that you did not run the database migrations. Please refer to the `migrations` folder in the source repository, or start the `lora-app-server` binary with the `--db-automigrate` flag. Also make sure to use separate databases for LoRa App Server and LoRa Server.

**Comment by mikumaycry** [comment]
Test with loraserver release 0.17.0, lora-app-server release 0.9.1.
I create a new postgresql container, add separate roles and corresponding databases following start guide.
Run both service from source code with --db-automigrate flag true.
And error still occurs.

**Comment by mikumaycry** [comment]
Sorry, I forget to rebuild the statics and ui resource before run main.go. Make clean and rebuild static resource could solve this issue.

**Comment by brocaar** [comment]
Could you close this issue when it has been resolved?
