### ISSUE TITLE
Error grpc: the connection is unavailable (code: 14)

### ISSUE THREAD

**Issue by hecko** [brocaar/lora-app-server#9]
please close this (now) blank case

**Comment by hecko** [comment]
OK, i think part of this issue is that information displayed in the web interface does not correlate with information I have in the postgres database. The postgres database has only one entry out of three in the web interface. How is this done that information is neither in redis, not in postgres but it still shows in the web interface? I feel like a total n00b here.

**Comment by RogerioCassares** [comment]
Hi @hecko , i'm having the same problem. could you help me, please? I'm in a big trouble :/

What you have done to soluntion this case, please?

**Comment by brocaar** [comment]
@RogerioCassares https://forum.loraserver.io/ is a better place for support questions 👍
