### ISSUE TITLE
Admin password recovery?

### ISSUE THREAD

**Issue by iBrick** [brocaar/lora-app-server#91]
Hi, Looks like my password is lost for 'admin' user or it doesn't work for some reason.
Is there any way to see it or change? In postgres I see it is hashed by sha512. How to change password?

**Comment by brocaar** [comment]
You could reset it in the database to this value (`admin`):
https://github.com/brocaar/lora-app-server/blob/master/migrations/0014_users_and_application_users.sql#L43

**Comment by iBrick** [comment]
Great, thank you for help!
