### ISSUE TITLE
Send Class C downlink messages through MQTT 

### ISSUE THREAD

**Issue by gkov9** [brocaar/lora-app-server#93]
Hello Orne,

This is really a "feature" comment and not an "issue" one. I would suggest to handle all payload functions to be handled "centrally". Today, Class A up and downlink is handled through MQTT, while Class C downlink is handled by LoRa App Server API. Don't you think it would be more useful to have a one channel payload handling (trough MQTT)?

**Comment by brocaar** [comment]
Please note that both Class-A and Class-C can be scheduled through the gRPC / REST API and MQTT. Under the hood, the scheduling is handled centrally. These are just two different interfaces to schedule.

**Comment by gkov9** [comment]
Hello,

Does this mean that if I publish a tx message to MQTT (and the end node is set to Class C) then the message is sent immediatelly through the gateway?

**Comment by brocaar** [comment]
@gkov9, yes that is correct.

**Comment by ehsanmqn** [comment]
Dear @brocaar 
I am wondering about the structure of tx messages. When I use the following format, tx message will show in the application server frame log section:
{
    "fcnt": 3,
    "fport": 1,
    "applicationID": "1",
    "applicationName": "environment-sensor",
    "nodeName": "node1",
    "devEUI": "0102030405060709",
    "data": "MjUsMTUsICAgICAgIDAsICAgICAgIDAsICAg"
}

but for the following structure data does not appear on the application server. It seems that data does not send at all. Please guide me and if is it possible give me a good reference about these topics.

**Comment by ehsanmqn** [comment]
Dear @brocaar 
I am wondering about the structure of tx messages. When I use the following format, tx message will show in the application server frame log section:
{
    "fcnt": 3,
    "fport": 1,
    "applicationID": "1",
    "applicationName": "environment-sensor",
    "nodeName": "node1",
    "devEUI": "0102030405060709",
    "data": "MjUsMTUsICAgICAgIDAsICAgICAgIDAsICAg"
}

but for the following structure data does not appear on the application server. It seems that data does not send at all. Please guide me and if is it possible give me a good reference about these topics.
{
    "data": "MjUsMTUsICAgICAgIDAsICAgICAgIDAsICAg"
}
