### ISSUE TITLE
Lora-app-server not working

### ISSUE THREAD

**Issue by vikkymahdrey** [brocaar/lora-app-server#99]
I have configured Lora-app-server as per LORA Server documentations;
I ran loraserver as "sudo systemctl start loraserver" and getting successful active status from "sudo systemctl status loraserver".

But i'm getting inactive as for lora-app-server in case of "sudo systemctl status lora-app-server";
I don't know where i'm doing mistake.

Would you please help me on this

**Comment by brocaar** [comment]
Please check the logs to see the returned error :-)

Alternatively, run the following command from the cli:

```bash
set -a
source /etc/default/lora-app-server
lora-app-server
```
